### ISSUE TITLE
Can I add require.js and grunt to build in dependancies into a single p5.play.js lib?

### ISSUE THREAD

**Issue by Jared-Sprague** [molleindustria/p5.play#10]
Hey @molleindustria! 
I've got a question for you.  I ran into a problem with sprite sheets because when an Animation is added to a Sprite, .clone() is called on the animation.  This doesn't work for sprite sheet Animations because it doesn't deep clone the state.  What I need is a way to deep clone the object.  There is a popular JavaScript library https://lodash.com/ that has a really nice cloneDeep() method, that would make this operation so easy, efficient, and browser compatible.  It totally works because I tested it and it makes sprite sheets work with Sprites.  This example is with lodash: http://scripta.co/p5.play/examples/index.html?fileName=sprites_with_sheet.js

So on to my question. Is it ok with you if I add require.js and grunt to build lodash.js into a single p5.play.js lib? 

This would also add all the other benifits of having grunt i.e. magnification, and doc generation.

This is the last problem I have to solve before I'm ready to make a Pull Request for sprite sheets.

Thanks!

**Comment by molleindustria** [comment]
Hi Jared,
thank you for doing this. I'm still a noob in both javascript and github.
The clone function is actually not a general deep cloning solution but a pretty simple custom deal:
https://github.com/molleindustria/p5.play/blob/a6896817ec38f402df908de6d51df01f75de6d7c/examples/lib/p5.play.js#L3183
I haven't had the time to examine your implementation closely but maybe you can expand that to copy the state and anything else that needs to be unique for each instance? For example I don't think it would be necessary to clone all the information regarding the position of each frame or tile. 

I looked into deep cloning and I couldn't find any option that didn't involve dependencies. The idea is to make a library that even beginners could tweak. Wouldn't adding require, grunt and a library increase the complexity?

**Comment by Jared-Sprague** [comment]
@molleindustria Thanks for the reply!  That's all I wanted to know!  I had a feeling that you were intentionally avoiding dependencies, which is why I asked.  I totally don't mind expanding the .clone() for Animaiton to make it work with sprite sheets.  Stay tuned!  If you want to take a look at my implementation I have it on a branch "sprite_sheets" on my fork here: 
https://github.com/Jared-Sprague/p5.play/tree/sprite_sheets
