### ISSUE TITLE
Instance mode with p5.play

### ISSUE THREAD

**Issue by ycatch** [molleindustria/p5.play#12]
Hi, there.

I tried p5.js and p5.play in instance mode, like this.

However, it stay loading...

Please tell me, is p5.play running in Instance mode?

```html
<body>
 	<div id = "p5Canvas"></div>
 	<script src="http://cdnjs.cloudflare.com/ajax/libs/p5.js/0.4.7/p5.min.js"></script>
 	<script src="/js/p5.play.js"></script>
 	<script>
 	var img
 	var s = function(sketch) {
 		var x = 100; 
 		var y = 100;
 		sketch.setup = function() {
 			sketch.createCanvas(800,400);
 			sketch.background(200);
 			sketch.fill(255);
 			img = sketch.createSprite(400, 200, 50, 50);
 		};
 
 		sketch.draw = function() {
 			sketch.drawSprites(img);
 		};
 	};
 
 	var myp5 = new p5(s, "p5Canvas");
 	</script>
 </body>
```

**Comment by GoToLoop** [comment]
Indeed w/ another sketch I've tried, I've got "Uncaught ReferenceError: createVector is not defined".
Seems like p5.play assumes p5.js' API is always globally available. Dunno...

```html
<meta charset=utf8>
<script src=http://p5js.org/js/p5.min.js></script>
<script src=http://p5play.MolleIndustria.org/lib/p5.play.js></script>

<script>

const s = function (p) {
  var sprite;

  p.setup = function () {
    p.createCanvas(800, 600);
    p.fill('blue').stroke('red').strokeWeight(2.5).rectMode(p.CENTER);
    sprite = p.createSprite(p.width>>1, p.height>>1, 0100, 0100);
    s.velocity.x = p.random(-5, 5), s.velocity.y = p.random(-5, 5);
  }

  p.draw = function () {
    p.background(0350);
    p.drawSprites();
  }
};

onload = function() {
  new p5(s);
};

</script>
```

**Comment by Jared-Sprague** [comment]
"Seems like p5.play assumes p5.js' API is always globally available. Dunno..."

I think this is correct

**Comment by ycatch** [comment]
GoToLoop,  Jared-Sprague 
Thank you for your comment

I understand.

**Comment by molleindustria** [comment]
Hi, sorry for the late answer, I suck at gibhut!
Yes, it does assume that p5.js is globally available. I couldn't find a good example on how to make a library work in instance mode. In the example above what would be the best way to tell a library that the p5 stuff is inside "sketch"?

**Comment by GoToLoop** [comment]
Inside p5.js' "core.js" there's a "private" property called *_isGlobal*:
https://github.com/processing/p5.js/blob/master/src/core/core.js#L447  
And each library which needs to access the sketch's canvas demands its owner's **_p5_** reference.
And they all store that parameter as *_pInst* . Check out _**p5.Element**_'s constructor for example:
https://github.com/processing/p5.js/blob/master/src/core/p5.Element.js#L30

**Comment by deiga** [comment]
@toolness Could you elaborate how one uses p5.play in instance mode? The docs don't seem to have an answer and if I just try instance mode the `p5` object has no properties like `loadSpriteSheet`

**Comment by GoToLoop** [comment]
> Could you elaborate how one uses p5.play in instance mode?

Here's a more up-to-date online version of the my previous sketch:
https://Bl.ocks.org/GoSubRoutine/cf739128f389766f5d9cb631c9c358a6

```js
/**
 * p5.Play Instance Mode Example (v1.0)
 * GoToLoop (2019-Apr-04)
 *
 * https://GitHub.com/molleindustria/p5.play/issues/12
 * https://Bl.ocks.org/GoSubRoutine/cf739128f389766f5d9cb631c9c358a6
 */

"use strict";

new p5(p => {
  let bg, sprite;

  p.setup = function () {
    p.createCanvas(800, 600).mousePressed(reset);
    bg = p.color(0o350);
    sprite = p.createSprite(p.width>>1, p.height>>1, 0o100, 0o100);
    reset();
  };

  p.draw = function () {
    p.background(bg);
    bounce();
    p.drawSprites();
  };

  function reset() {
    sprite.setVelocity(p.random(-5, 5), p.random(-5, 5));
    sprite.shapeColor = '#' + p.hex(~~p.random(0x1000), 3);
  }

  function bounce() {
    const { position: { x, y }, width: w, height: h } = sprite,
          ww = w >> 1, hh = h >> 1;

    if (x < ww || x + ww >= p.width)   sprite.velocity.x *= -1;
    if (y < hh || y + hh >= p.height)  sprite.velocity.y *= -1;
  }
});
```
