### ISSUE TITLE
QuadTree breaks sprite group collisions when sprites go off screen

### ISSUE THREAD

**Issue by ghost** [molleindustria/p5.play#124]
Love p5.play! I use it in a class. I found a problem looking at a student project. If a sprite moves off screen and isn't removed, any subsequent collisions using a sprite group its in will break when quadTree is true. The following code shows the behavior. To see the error, let the first spawned block go off the screen. I've found subsequent collisions to break.

```
var player;
var pickups;
var count;

function setup() {
  createCanvas(200, 400);

  player = createSprite(100, 360, 20, 20);
  pickups = new Group();
  count = 0;
  //useQuadTree(false);
}

function draw() {
  background(240);

  player.overlap(pickups, playerPickupCollision);

  if (count >= 80) {
    var pickup = createSprite(random(10, 190), -10, 20, 20);
    pickup.velocity.y = 2;
    pickups.add(pickup);
    count = 0;
  }

  if (keyIsDown(LEFT_ARROW)) {
    player.setSpeed(-4, 0)
  } else
  if (keyIsDown(RIGHT_ARROW)) {
    player.setSpeed(4, 0)
  } else {
    player.setSpeed(0, 0)
  }

  drawSprites();
  count++;
}

function playerPickupCollision(p1, e1) {
  e1.remove();
}
```

I tried sorting through the quadTree code and got a bit lost.

**Comment by molleindustria** [comment]
to be honest js is so slow and frame-inconsistent that I was never even able to figure out if the quadtree really optimizes collisions. Easy solution: don't use it.

That's also the only part of the library I took from somewhere else and I only have a general idea of how it works. I wonder if the other contributors know how to fix this...

**Comment by playfulsystems** [comment]
No worries. Debugging resulted in my discovery of that useQuadTree function. Yeah, setting to false works as a fix. If I find the time, I'll see if I can make sense of it. Thanks.

**Comment by molleindustria** [comment]
oh, I thought that the quadtree was disabled until manually activated. This is a big problem.

**Comment by quinton-ashley** [comment]
Solved (better late than never) 6 years later haha in v2.2.5

I did some performance testing and the Quadtree actually optimizes collisions quite well if you have a lot of sprites. With over 200 sprites checking for bounces against each other the performance saving is like 50% of the time without the Quadtree.

The code added to the Quadtree didn't work though, for example updateBounds which I initially thought was the culprit.

```js
updateBounds() {
			//find maximum area
			var objects = this.getAll();
			var x = 10000;
			var y = 10000;
			var w = -10000;
			var h = -10000;

			for (var i = 0; i < objects.length; i++) {
				if (objects[i].position.x < x) x = objects[i].position.x;
				if (objects[i].position.y < y) y = objects[i].position.y;
				if (objects[i].position.x > w) w = objects[i].position.x;
				if (objects[i].position.y > h) h = objects[i].position.y;
			}

			this.bounds = {
				x: x,
				y: y,
				width: w,
				height: h
			};
			//print(this.bounds);
		}
```

Width/height of the bounds is not the maxX and maxY position if minX and minY are negative. Here is the corrected function:

```js
updateBounds() {
    //find maximum area
    var objects = this.getAll();
    if (!objects.length) return;
    var minX = objects[0].position.x;
    var minY = objects[0].position.y;
    var maxX = minX;
    var maxY = minY;
    
    for (var i = 0; i < objects.length; i++) {
	    if (objects[i].position.x < minX) minX = objects[i].position.x;
	    if (objects[i].position.y < minY) minY = objects[i].position.y;
	    if (objects[i].position.x > maxX) maxX = objects[i].position.x;
	    if (objects[i].position.y > maxX) maxX = objects[i].position.y;
    }
    
    this.bounds = {
	    x: minX,
	    y: minY,
	    width: abs(maxX - minX),
	    height: abs(maxY - minY)
    };
    //print(this.bounds);
}
```

The actual problem though was the code for removing an item from the Quadtree. That shouldn't even be attempted in my opinion, it is much easier to just rebuild it after a sprite is removed.

```js
// clear and rebuild the quadTree
this.p.quadTree.clear();
for (let s of this.p.allSprites) {
	if (!s.removed && s.collider) {
		this.p.quadTree.insert(s);
	}
}
```

I also think for p5.play to use the quadTree more effectively it should do automatic culling (removing objects that go to far offscreen as suggested in #192
