### ISSUE TITLE
SpriteSheets Broken in latest P5.play library

### ISSUE THREAD

**Issue by gtoast** [molleindustria/p5.play#125]
animation() call fails to animate.  Even the "Animation - sprite sheet" demo example fails to actually animate the spritesheet. 

Prints message:  Warning undefined frame 0 p5.js:12477

**Comment by adibbehjat** [comment]
+1

**Comment by molleindustria** [comment]
I encountered that too and I'm using an old version in my class. I'll try to investigate but these are not my changes...

**Comment by gtoast** [comment]
I think I found the source of this bug. I'll attempt a patch in a couple hours.

**Comment by SnipedCode** [comment]
Hi, I get very strange result with SpriteSheets. I can't get it work, I copy paste the exemple, image everything and still.... I saw a fix I changed the original file according to the mentioned modification but again, it's not working.. after a day trying and trying... is someone aware of a problem loading SpriteSheets ? please help me understand why I can't load my animation.

**Comment by galinabee** [comment]
I'm having this issue when trying to start up [http://molleindustria.github.io/p5.play/examples/index.html?fileName=animation.js]. Any suggestions?

**Comment by luyingzhang** [comment]
> I'm having this issue when trying to start up [this example](http://molleindustria.github.io/p5.play/examples/index.html?fileName=animation.js) Any suggestions?

restore to the version 0.5.4 can fix:

p5.prototype.image =
  function(img, sx, sy, sWidth, sHeight, dx, dy, dWidth, dHeight) {
  // set defaults per spec: https://goo.gl/3ykfOq
  if (arguments.length <= 5) {
    dx = sx || 0;
    dy = sy || 0;
    sx = 0;
    sy = 0;
    if (img.elt && img.elt.videoWidth && !img.canvas) { // video no canvas
      var actualW = img.elt.videoWidth;
      var actualH = img.elt.videoHeight;
      dWidth = sWidth || img.elt.width;
      dHeight = sHeight || img.elt.width*actualH/actualW;
      sWidth = actualW;
      sHeight = actualH;
    } else {
      dWidth = sWidth || img.width;
      dHeight = sHeight || img.height;
      sWidth = img.width;
      sHeight = img.height;
    }
  } else if (arguments.length === 9) {
    sx = sx || 0;
    sy = sy || 0;
    sWidth = _sAssign(sWidth, img.width);
    sHeight = _sAssign(sHeight, img.height);

    dx = dx || 0;
    dy = dy || 0;
    dWidth = dWidth || img.width;
    dHeight = dHeight || img.height;
  } else {
    throw 'Wrong number of arguments to image()';
  }

  var vals = canvas.modeAdjust(dx, dy, dWidth, dHeight,
    this._renderer._imageMode);

  // tint the image if there is a tint
  this._renderer.image(img, sx, sy, sWidth, sHeight, vals.x, vals.y, vals.w,
    vals.h);
};
