### ISSUE TITLE
Warning....undefined frame 0

### ISSUE THREAD

**Issue by karneaud** [molleindustria/p5.play#128]
I'm using P5JS 0.5.6 with your library and I have a in the 

```
setup() {
var sprite = createSprite(0+400 * x + 200 , 0+400 * y + 200, 400,400 );
    sprite.addAnimation('singing'
      ,loadAnimation('assets/images/reject'.concat(i+1,'b.png')
      ,'assets/images/reject'.concat(i+1,'a.png'))
    );

    sprite.shapeColor = color(random(255), random(255), random(255));

....
```

however when running the sketch I get in the console

> Warning undefined frame 0

The images are loaded via the `preload()` but they do not appear on the canvas despite having `drawSprites` in the `draw()`

any suggestions as to what this might be?

**Comment by islemaster** [comment]
Hi there!  Thanks for reporting.  This sounds like an issue that got fixed _very_ recently (four days ago) in https://github.com/molleindustria/p5.play/pull/127.  Can you try this with the [latest version of p5.play.js](https://raw.githubusercontent.com/molleindustria/p5.play/master/lib/p5.play.js), or confirm you're already on the latest version from GitHub?

Thanks! Brad

**Comment by karneaud** [comment]
@islemaster I think so. I'm pulling from the master branch

**Comment by islemaster** [comment]
I must have missed something then.  I'll try and reproduce the issue with something as close to your example code as I can get.

**Comment by islemaster** [comment]
Hi @karneaud - here's what I've found so far.  The following code correctly renders a sprite with an animation with no warnings for me on [the example page](http://molleindustria.github.io/p5.play/examples/index.html) (just replace the whole contents of the textbox and click "Run").  I tried to stick fairly close to code snipped you provided - the biggest change is that I'm referring to images that are available on the examples page.

```javascript
function preload() {}

function setup() {
  createCanvas(800, 300);
  
  var x = 0;
  var y = 0;
  var i = 0;
  
  var sprite = createSprite(0+400 * x + 200 , 0+400 * y + 200, 400,400 );
    sprite.addAnimation('singing'
      ,loadAnimation('assets/ghost_standing000'.concat(i+1,'.png')
      ,'assets/ghost_standing000'.concat(i+2,'.png'))
    );
    
  sprite.shapeColor = color(random(255), random(255), random(255));
}

function draw() {
  background(255, 255, 255);
  drawSprites();
}
```

The examples page is using p5.js v0.4.21 (available in this repository at examples/lib/p5.js), so it seems very possible that you're encountering a compatibility issue with v0.5.6 - I'll check that next.

**Comment by UjjwalSingh77** [comment]
me too

**Comment by jmmcd** [comment]
I encountered this error message today with current p5js and p5.play. The fix was to move my line of code from `preload` to `setup`:

```js
  zombie.addAnimation("walk", zombie_anim);
```

**Comment by Ish7R** [comment]
Same thing happened to me, took spaces out of the original png files and uploaded again. it worked fine.
