### ISSUE TITLE
addImage does not resize image to dimensions of sprite

### ISSUE THREAD

**Issue by karneaud** [molleindustria/p5.play#129]
if you create a sprite with the dimensions less or greater than the an image's and then add the image to the sprite ...shouldn't the image be resized to fit the dimensions of the sprite?

If not shouldn't there be some way to do it from the sprite?

**Comment by molleindustria** [comment]
Hopefully fixed by this, I'm still unclear on how the width and heights are handled now to be honest
https://github.com/molleindustria/p5.play/commit/183dfe86614b1b2fd3314ba742273e6a146b45c6
