### ISSUE TITLE
Groups and zombie's

### ISSUE THREAD

**Issue by mtareiling** [molleindustria/p5.play#135]
Hey it's me again i was also the guy on #135. So i was wondering if i wanted to make a main character and a zombie and when the character kills the zombie that then 2 zombies spawn and if you kill those 3 and so further on. can someone please help? i quite understadn how groups work but im still with this issue.

**Comment by mtareiling** [comment]
im sorry it's issue #134

**Comment by islemaster** [comment]
Hello again!  I'm happy to help a bit more, but your question is starting to be more of a general programming question than one particularly about p5.play.

First, what do you have working so far?  For example, have you got a zombie and a main character on the screen?  Can you move the main character around?  Posting a link to your sketch (your code) would be helpful - [gist.github.com](https://gist.github.com/) is a great tool for this if the code is not already online somewhere.

It sounds like the particular group question you're asking is about how to know when a group is empty, and how to add more sprites to that group.  In your case, it would go something like this (not complete code):
```javascript
// At the top of your sketch...
var zombieGroup;
var numZombiesToSpawn = 1;

// Somewhere in your setup() function...
zombieGroup = new Group();

// Somewhere in your draw() function...
// If there are no more zombies...
if (zombieGroup.length === 0) {
  // ...add more zombies!
  for (var i = 0; i < numZombiesToSpawn; i++) {
    // Do your zombie setup here - set the animation, size, etc...
    var newZombie = createSprite(...)

    // Make sure all zombies go into zombieGroup
    zombieGroup.add(newZombie);
  }

  // Make more zombies spawn next time this happens...
  numZombiesToSpawn += 1;
}
```

**Comment by mtareiling** [comment]
I am quite far i have made a Free website the link is here: https://mnmgames.000webhostapp.com/


I am not a beginner i think/ hope but nie i needed Some groups so could make a spanning system. But i think youre last post is enough i think.
But i do like to bos what you think About the game Right now. Btw controles are: w, a, d, mouse button

Ps. Sorry doe my  crappy grammer

**Comment by islemaster** [comment]
Oh, I see!  You have a lot working already, and your challenge now is not just a spawning system, but generalizing from one zombie sprite to many zombie sprites.  That's going to involve changing every place you use `red` (your zombie) to code that either operates on the whole zombie group, or on each zombie in turn.

* In places where you are changing positions and animations, you'll want to iterate through the zombie group and deal with one sprite at a time:
  ```javascript
  for (var i = 0; i < zombieGroup.length; i++) {
    var red = zombieGroup[i];
    if(sprl.position.x >= red.position.x){
      red.changeAnimation("zombier");
      red.velocity.x = 1;
    }
    // Same for making zombie turn left...
  }
  ```
* Collision functions (bounce, overlap, etc) can be used with entire groups instead of individual sprites:
  ```
  if (sprl.overlap(zombieGroup)) //laat er helth afgaan als man de zombie aanraakt.
    health = health - 1;
  ```

Good luck!  Also, your hero has a very powerful jump! :grin:
