### ISSUE TITLE
Friction documentation is wrong

### ISSUE THREAD

**Issue by Carlingr** [molleindustria/p5.play#137]
Documentations states that ```sprite.friction=1;``` will be no friction. In actuality it is ```sprite.friction=0;```. ```sprite.friction=1``` is no movement.

**Comment by islemaster** [comment]
Thanks for pointing this out!

The [documentation comment](https://github.com/molleindustria/p5.play/blob/master/lib/p5.play.js#L828-L838) is up-to-date, so this issue will be resolved next time we regenerate/redeploy the documentation.  That's a separate process for the two places where the documentation lives:

* [p5play.molleindustria.org](http://p5play.molleindustria.org/docs/classes/Sprite.html#prop-friction) will need to be updated by @molleindustria.
* [molleindustria.github.io/p5.play](http://molleindustria.github.io/p5.play/docs/classes/Sprite.html#prop-friction) can be updated by any maintainer - I'll do this shortly (for future reference, [instructions are here](https://github.com/molleindustria/p5.play/pull/80)).  My hope is that [someday soon this is auto-deployed](https://github.com/molleindustria/p5.play/pull/80#issuecomment-204172073).

Assigning this task to myself and @molleindustria to track.

**Comment by islemaster** [comment]
Solved by #150.
