### ISSUE TITLE
Add a unit test suite

### ISSUE THREAD

**Issue by toolness** [molleindustria/p5.play#14]
I'd like to add a simple unit test suite in the style of p5's test suite (mocha, phantomJS, Travis CI integration, [nyan cat test formatter](https://github.com/mattsears/nyan-cat-formatter/blob/master/nyan_example.gif), etc). This way future bugs can have regression tests easily written for them.

To start I'd like to just add the test infrastructure along with a regression test for #13.

@molleindustria does this sound okay?

**Comment by molleindustria** [comment]
Yeee I have no idea of what you are talking about but it sounds great. I'm guessing that would not change the code itself but only entail some extra files in the repo, am I correct?

**Comment by toolness** [comment]
Yep, exactly! Basically we'd just add a `test` directory at the root of the repository that looks something like [this](https://github.com/processing/p5.js/tree/master/test) and we'd hook it up to a service called [Travis](https://travis-ci.org/) that runs those tests whenever new code is committed to the repository, to make sure that existing functionality doesn't break.
