### ISSUE TITLE
Firefox global function "Animation"Issue

### ISSUE THREAD

**Issue by apardo04** [molleindustria/p5.play#141]
Console Log returns this on Firefox: p5 had problems creating the global function "Animation", possibly because your code is already using that name as a variable. You may want to rename your variable to something else.

Has anyone had this issue or have a fix? None of my variables are named Animation

**Comment by bomoko** [comment]
@apardo04 as discussed on the p5.js thread (just to repeat it here) it seems as though there's a window.Animation() function in FF, and so that's causing the namespace collision.

**Comment by bomoko** [comment]
Quick update - it's definitely the Web Animations API in FF doing this.
If you set **dom.animations-api.element-animate.enabled** in your FF preferences to **false**, then rerun the script, you'll find that the "Animation" object is no longer part of the global scope.

**Comment by apardo04** [comment]
Sorry, for late response, but thanks for clearing that up.
