### ISSUE TITLE
Multiple animations affect each other's frame rate?

### ISSUE THREAD

**Issue by charcoal1** [molleindustria/p5.play#145]
I've noticed that when more than a few animations are added to the canvas the frame rate ebbs and flows in frame rate. Two or more animations tend to induce the speed. Has anyone else noticed this?

**Comment by SaintPepsi** [comment]
Can you give a [minimal working example](https://stackoverflow.com/help/mcve)? Thanks.

**Comment by quinton-ashley** [comment]
example not provided, closing
