### ISSUE TITLE
Animation.frameDelay documentation is wrong

### ISSUE THREAD

**Issue by touyou** [molleindustria/p5.play#147]
Documentation states `Animation.frameDelay`'s default value is 2, but actually the code initializes `this.frameDelay` to 4.
And I also found typo in this documentation `anymation`. I think it should be `animation`.

https://github.com/molleindustria/p5.play/blob/master/lib/p5.play.js#L3338-L3347

**Comment by islemaster** [comment]
Solved by #150.
