### ISSUE TITLE
Downloading to use as a newcomer

### ISSUE THREAD

**Issue by fergfluff** [molleindustria/p5.play#156]
Hello, I'm a fairly new person to p5.js and p5.play. Thank you for creating this! 

I wanted to share that I had a some trouble putting the library in the right place so that my project could reference it. Granted, I'm new to coding but I thought maybe others who are beginner/intermediate are having the same problem, and aren't successfully able to get started with the library at all.

Can the Get Started instructions explain a few extra optional steps for those who already have p5 libraries on their local computer? https://github.com/molleindustria/p5.play/wiki/Get-Started

I got lost because the instructions say to include in my html file <script src="lib/p5.play.js" type="text/javascript"></script>, but don't mention where to put it if you're adding it to an already existing p5 project. (In the end I moved the downloaded "p5.play-master" folder into my code's libraries folder, and used this reference in my html file instead 	<script src="libraries/p5.play-master/lib/p5.play.js" type="text/javascript"></script>. )

Maybe there's a better way to save it... but this is what made sense to me after only recently working locally on my computer after learning p5.js online with the alpha.editor.p5js.org.

Just a few extra steps on the Getting Started page to help orient people coming from this direction will help a lot!

Thanks again! Great library!

**Comment by quinton-ashley** [comment]
Will do!

**Comment by quinton-ashley** [comment]
https://github.com/molleindustria/p5.play/wiki/Get-Started
