### ISSUE TITLE
loadImage accepts base64 images but not loadAnimation

### ISSUE THREAD

**Issue by noordo** [molleindustria/p5.play#158]
Hello,

It is very useful to be able to replace (on website like jsfiddle) the following line of code 
`ghost = loadImage("assets/ghost_standing0001.png");`
by this one:
`ghost = loadImage(base64_ghost_standing0001);`
("base64_ghost_standing0001" is a javascript variable containing the code of the figure in base64)

The "loadAnimation" command does not accept some  base64 images as arguments : it would be so useful to create animations on jsfiddle.net like this :
`ghost = loadAnimation(base64_ghost_standing0001,base64_ghost_standing0002,base64_ghost_standing0003, base64_ghost_standing0004,base64_ghost_standing0005,base64_ghost_standing0006,base64_ghost_standing0007);`

Thanks

**Comment by quinton-ashley** [comment]
loadAnimation takes p5.Image objects, not base64 image data. Load the images first and then use them with loadAnimation
