### ISSUE TITLE
CodePen & P5.PLay

### ISSUE THREAD

**Issue by computhinkers** [molleindustria/p5.play#159]
Noticing the CodePen and P5.play do not "Play" well together.  We are frequently running into issues with images.  I tried to find other issues that might help resolve these but to no avail.  

Which external resources do you suggest when using p5.play in codePen.io?

**Comment by quinton-ashley** [comment]
It is likely you will encounter CORS errors when using p5.play on codepen since the images you reference would be from a different site. Either store the images in JS (technically possible) or try repl.it instead.
