### ISSUE TITLE
Sprite with a loaded image doesn't show on screen

### ISSUE THREAD

**Issue by salvatorescarfone** [molleindustria/p5.play#160]
I tried to load an image into a Sprite, but this never shows on screen.
I think i correctly followed the example but there's no way i manage to see the Sprite.

I attach my sketch, index and image files so you can exactly see what i've written, thanks in advance for the support!

[prova1.zip](https://github.com/molleindustria/p5.play/files/1842899/prova1.zip)

**Comment by molleindustria** [comment]
The zip doesn't include the p5, p5.play, etc libraries. Once you add them it works
