### ISSUE TITLE
play with socket.io

### ISSUE THREAD

**Issue by bizarrr** [molleindustria/p5.play#161]
Hit there,

thank you for this awesome library. 
I try to make a multiplayer game , but it seems that p5.play is not compatible 
with socket.io (no error message , but no sprite is displayed).
Don't know if someone tried to test it ?...

**Comment by islemaster** [comment]
I've never worked with Socket.IO, but looking at there documentation I don't see any reason they wouldn't be compatible with p5.play.  Do you have any example code you can share?

**Comment by quinton-ashley** [comment]
Should work fine. Example code not provided by issue creator, closing
