### ISSUE TITLE
remove

### ISSUE THREAD

**Issue by cesarrodas** [molleindustria/p5.play#162]
Hey I think I may have seen this issue in the past before. 
I'm trying to remove sprites from the screen. 
I am trying removeSprites from a group as well a looping through a group and calling remove on each sprite manually. They both freeze the screen without throwing errors. I cannot get rid of any sprite. 
Is there a fix for this? thanks for any help

edit: the clear method doesn't get rid of sprites on the screen. It doesn't freeze but the sprites are still there. Also I can use remove manually on certain sprites but others make the screen freeze happen. I was trying to figure out what was different in those sprites but i am not able to to.

**Comment by molleindustria** [comment]
I would need to see the code
