### ISSUE TITLE
Support for sprites created from a polygon or path

### ISSUE THREAD

**Issue by dhowe** [molleindustria/p5.play#163]
I'd like to create sprites by specifying a (potentially complex) shape at runtime, either via a polygon or path. Is this (or will this be) supported? thanks!

**Comment by 7ammer** [comment]
This might be useful:
https://github.com/bmoren/p5.collide2D

**Comment by molleindustria** [comment]
The easiest way is to override the draw function and use the normal p5 drawing functions
http://molleindustria.github.io/p5.play/examples/index.html?fileName=sprite9.js

Overlapping for polygons can be checked with the library above but for their resolution you'd need a physics engine like Box2d

**Comment by dhowe** [comment]
right, thanks... I was looking for a simpler way to do collisions/bouncing of glyphs as the Box2d api has been pretty difficult for learners

**Comment by 7ammer** [comment]
Matter.js + p5.js maybe easier?
https://www.youtube.com/watch?v=urR596FsU68

**Comment by dhowe** [comment]
indeed, looks promising
