### ISSUE TITLE
No package release on GitHub

### ISSUE THREAD

**Issue by jonashw** [molleindustria/p5.play#164]
[This package](https://www.jsdelivr.com/package/gh/molleindustria/p5.play) doesn't have any [GitHub release](https://help.github.com/articles/about-releases/). Could you please create one, so that people can use this project from CDN?

**Comment by MartinKolarik** [comment]
@jonashw before there's a release, you can use an url with the latest commit hash instead: https://cdn.jsdelivr.net/gh/molleindustria/p5.play@42cd19c39f6f508e4a73c20eaaeb490b97022840/ (this is a recently added jsDelivr feature)

**Comment by GoToLoop** [comment]
Until then, another CDN option is RawGit.com: :-D
https://RawGit.com/molleindustria/p5.play/master/lib/p5.play.js

I hope when a release is finally set up, they could also include a "main" entry inside "package.json" pointing out straight to the "p5.play.js" file.

A minified version would be gr8 too.  ;-)

**Comment by MartinKolarik** [comment]
jsDelivr does minification too: https://cdn.jsdelivr.net/gh/molleindustria/p5.play@42cd19c39f6f508e4a73c20eaaeb490b97022840/lib/p5.play.min.js

**Comment by GoToLoop** [comment]
I know that! But RawGit.com doesn't have an auto minified feature.  O_o

**Comment by MartinKolarik** [comment]
Haha ok, fair enough 😄

**Comment by GoToLoop** [comment]
Notice that in order for https://JsDelivr.com to work for https://GitHub.com, the release labels gotta follow the https://SemVer.org 's semantics!

Having the repo on the https://NpmJs.com would be gr8 too!

**Comment by MartinKolarik** [comment]
>Notice that in order for https://JsDelivr.com to work for https://GitHub.com, the release labels gotta follow the https://SemVer.org 's semantics!

Not necessarily, it's just a recommendation. Any version format works but you don't get version ranges if it's not semver.

**Comment by GoToLoop** [comment]
>  ... but you don't get version ranges if it's not SemVer.

IMO, those ugly long hashes are workarounds for lack of SemVer.  :-P

**Comment by MartinKolarik** [comment]
Of course they are. For rawgit you need to use hashes too if there are no releases, otherwise there's no way to know where the cached file should update.

**Comment by GoToLoop** [comment]
> For RawGit you need to use hashes too if there are no releases,

Nope! I've posted a https://RawGit.com link for the very fact there's no release in this GitHub repo! o_o
https://RawGit.com/molleindustria/p5.play/master/lib/p5.play.js

**Comment by MartinKolarik** [comment]
Yes but as I said there's no way to know where the cached file should update in that case. Originally the URL you posted would be cached forever and never update. Many people used it incorrectly so eventually the rawgit author had to change it and master branch URLs are now cached for 24 hours AFAIK. The advantage is prettier links, the disadvantage is worse caching. For other branches the hashes are still necessary.

**Comment by GoToLoop** [comment]
> ... so eventually the RawGit author had to change it and master branch URLs are now cached for 24 hours AFAIK.

Well, so we just need at most merely 24 hours to get the latest p5.play library. ^_^

**Comment by quinton-ashley** [comment]
fixed with release v2.0.1
