### ISSUE TITLE
Documentation site

### ISSUE THREAD

**Issue by molleindustria** [molleindustria/p5.play#165]
Hey all, I suspect the API reference and the examples hosted on the original p5.play site (http://p5play.molleindustria.org/) are getting misaligned with the library. 

I suppose the best solution would be to turn it into a github site but I have not experience in that. Can you even have a YUIdoc reference hosted on github? Or maybe there is some way to automate or open the reference creation to other contributors?

Do you have any thoughts on that?

**Comment by islemaster** [comment]
Hi @molleindustria!

We've already got the documentation hosted on GitHub at http://molleindustria.github.io/p5.play/. It's attached to the repository so anyone can suggest an update by opening a pull request here.  We don't have it auto-updating on every build yet, but it's definitely possible, and in the meantime any maintainer (yourself, @toolness, or I) can publish a documentation update.

Back in 2016 @toolness mentioned (https://github.com/molleindustria/p5.play/issues/57#issuecomment-202535945) that you could make http://p5play.molleindustria.org/ point to these hosted GitHub docs by:

- Adding a CNAME file in the root of the gh-pages branch containing the text "p5play.molleindustria.org".
- Set up a CNAME DNS record for p5play.molleindustria.org that points to molleindustria.github.io.

**Comment by molleindustria** [comment]
Oh wow, I totally missed that. Awesome, I redirected the domain. Thank you so much for all your work!

**Comment by islemaster** [comment]
Awesome!  That will simplify life for everyone hunting for documentation.  Thank you!
