### ISSUE TITLE
Hide/Visible Sprite and React modal window

### ISSUE THREAD

**Issue by Nadoni** [molleindustria/p5.play#167]
**Issue 1.** When I set functions _onMouseOver, onMouseOut, onMousePressed_ to my spritesheet it looks prety well (Imagine: a spell attack using a tooltip of damage and cost). After that I want to do something and hide my sprite using _.visible = false_. But the sprite is still there, and I can also touch it, although I do not see it. I tried use _.mouseActive = false;_ but all the callbacks came back with "true". Because of that, 

> "Note: automatically set to true if the functions onMouseReleased or onMousePressed are set."

How can I make such sprites completely hidden (untouchable) with listeners for a while? And then to get it reversed?

**Issue 2.** When I use _react-portal_ module or _ReactDOM.createPortal_ it doesn't  overlap/block pop up mouseListeners from canvas, which is underneath. I can still click on the sprite through the modal window... It's crazy...
I try to play with z-index in style.css and "inline mode"... nothing happening.
**Info: canvas sketch exdends P5Wrapper class which inside GameLevelClass component.**

Some code: 

```
Modal.setAppElement('#modal');
const customStyles = {
    overlay: {
        zIndex: 999
    }
};

const customStylesGame = {
    overlay: {
        zIndex: -10
    }
};
export default class GameInit extends React.Component {
. . .
. . .
render() {
        return (
            <div>

                <Modal
                    isOpen={this.state.modalIsOpen}
                    onRequestClose={this.closeModal}
                    style={customStyles}
                    contentLabel="Task Modal"
                >
                    <ArithmeticTask style={customStyles} checkAnswer={this.checkAnswer}/>
                </Modal>

                //canvas here -> <GameLevelClass style={customStylesGame} onSpellClick={(e) => this.handleClick(e)}
                                answer={this.state.answer}/>}

            </div>


        );
    }
}
```

**Comment by Nadoni** [comment]
@islemaster, thanks for advice. Yes I use that P5Wrapper and you know what a pain it is to get them right (p5.js, p5.play.js and reactjs). 

```js
import React, {Fragment} from "react";
import p5 from "p5";
import 'p5/lib/addons/p5.dom';
import 'p5/lib/addons/p5.sound';
import 'p5/lib/addons/p5.play';

export default class P5Wrapper extends React.Component {
    constructor(props){
        super(props);

    }
    componentDidMount() {
        this.canvas = new p5(this.sketch, this.wrapper);
        if (this.canvas.myCustomRedrawAccordingToNewPropsHandler) {
            this.canvas.myCustomRedrawAccordingToNewPropsHandler(this.props);
        }
    }
    componentWillUnmount() {
        this.canvas.remove();
    }
    render() {
        return (
            <Fragment>
                <div className="flex-wrap-row">
                    <div className="button button--primary" onClick={this.props.logout}>Logout</div>

                </div>
                <div ref={wrapper => (this.wrapper = wrapper)} />
            </Fragment>
        )
    }
}
```

And I've actually, kind of, solved this problem by unmounting of listeners. And mount them again after a while. Something like:
```js
...
currentHero.Skills.forEach(skill => {
                        let tempSkill = skill.GetSpriteSkillObject();
                        tempSkill.visible = true;
                        tempSkill.onMousePressed = () => onSkillClick(skill);
                        tempSkill.onMouseOver = () => onSkillOver(skill);
                        tempSkill.onMouseOut = () => onSkillOut(skill);

                    })
...
currentHero.Skills.forEach(skill => {
                let tempSkill = skill.GetSpriteSkillObject();
                tempSkill.visible = false;
                tempSkill.onMousePressed = null;
                tempSkill.onMouseOver = null;
                tempSkill.onMouseOut = null;
            });
...
```
But the implementation of some untouchable/unmountable property of method for sprite in your library would be nice) I want actually use `sprite.remove()`, but not at all remove my sprite and then turn it back by something like `sprite.mount()` and save all its behaviour.
I also have questions:
**Question 1.** When will you implement this feature #166 ? I've already added this into my working p5.play.js lib and use it:
```js
loadAnimationCompleted = (animation) => {
        //TODO Animation.onfinish = finishHandler;
        this.SpriteObject.changeAnimation(animation);
        return new Promise(resolve => {
            this.SpriteObject.animation.onComplete = () => {
                if (animation === 'fall') {
                    if (this.Type === 'AI') {
                    }
                    this.SpriteObject.animation.stop();
                    this.SpriteObject.IsCompleteTurn = false;
                    return resolve();
                }
                this.SpriteObject.animation.changeFrame(0);
                this.SpriteObject.changeAnimation('stance');
                resolve();
            }
        })
    };
```
**Question 2.** When this #140 support would be implement in your repo ? Because it still have problem with spritesheets position and offset. I've also changed these lines in my working lib to:
```js
 ...
pInst.image(this.image, x, y,
                frameToDraw.width, frameToDraw.height,frameToDraw.x, frameToDraw.y,  dWidth, dHeight);
...
```
```js
...
pInst.image(this.spriteSheet.image, this.offX, this.offY,  frame_info.width,
                            frame_info.height,frame_info.x, frame_info.y,  frame_info.width, frame_info.height);
...
```
**Question 3.** When will you upload your lib into npm or/and add to p5 package?) I just want tap `npm install p5` or `p5.play` and use all of this collaborative stuff)

**Comment by fenicento** [comment]
> **Question 3.** When will you upload your lib into npm or/and add to p5 package?) I just want tap `npm install p5` or `p5.play` and use all of this collaborative stuff)

+1, that would be awesome

**Comment by quinton-ashley** [comment]
I made an npm package for this repo but a better (smaller) one is hopefully coming soon! The rest of the content of this issue either was fixed already or is in the wontfix category.
