### ISSUE TITLE
Clarify License for Artwork

### ISSUE THREAD

**Issue by i3games** [molleindustria/p5.play#169]
While the code is under LGPL, can you clarify if/how the artwork in the examples can be used (possibly under a CC based license)?

**Comment by quinton-ashley** [comment]
@molleindustria I would like to know the answer to this as well! I also think we should upgrade the license to GPL-3.0

**Comment by molleindustria** [comment]
Consider the graphics CC0. 
P5.js is under LGPL-2.1 so I'd stick with that since it depends on it.
