### ISSUE TITLE
Group collisions are a bit strange

### ISSUE THREAD

**Issue by tatomarchioli** [molleindustria/p5.play#171]
I'm building this "platform game" and i'm trying to create the platforms, grounds and walls of the map with blocks. 

Here is an print of the current state:

![image](https://user-images.githubusercontent.com/7478516/46820315-4ac65f80-cd5c-11e8-8111-07a5a8da8359.png)

The thing is, when the player object (the strange blue block) is running on top of the ground (the array of squares bellow the strange block) the collision detection should only detect the collision between the player foot and the ground top, but sometimes I get some glitches because some collisions are beeing detected between the sides of the player and the sides of the block, even if the blocks are perfectly aligned. 

The player object has a gravity force that's constantly pushing him down, so at every frame a collision is detected, then the player is displaced to it's correct location, then the collision is detected again because he will touch the ground block again and the cycle repeats. I think that this is one of the causes of the problem.

I tried to modify the lib code but I'm couldn't find a nice way to fix it. I actually managed to create another type of collider that considers only the top and the bottom, but I didn't like this aproach because I thing the lib should handle this. 

If there's a better way to do this kind of thing, please let me know. I'm in the learning stages so this might not be a big issue.

**Comment by Suxsem** [comment]
I'm experiencing the same issue.

**Comment by quinton-ashley** [comment]
I've experienced this too. This is probably an issue with number rounding incorrectly placing the player slightly below a block. I will fix this when I add a tile system to p5.play

Follow #186
