### ISSUE TITLE
setCollider makes sprite disappear

### ISSUE THREAD

**Issue by jimboweb** [molleindustria/p5.play#176]
Having an issue in the game I'm making here:

https://repl.it/@JimStewart1/LiamsGame

On line 33 I have `setCollider('circle')` commented out. When I uncomment it, then the sprite's image disappears when my sprite moves up. The sprite is still there bouncing around because the camera is following it, but you can't see it.

**Comment by quinton-ashley** [comment]
Try scaling the image to the size you want first, without using the scale property of the sprite.
