### ISSUE TITLE
Bad spritesheet behaviour

### ISSUE THREAD

**Issue by GabriMagic** [molleindustria/p5.play#177]
Good morning
I am trying to use some sprite-sheet to create a simple animation, but I have some problems, and it does not work properly, this is the sprite-sheet:

![image](https://user-images.githubusercontent.com/6409499/52406896-b62ffc00-2ac6-11e9-9db6-30d944b91642.png)

(I am using this cdn https://s3-us-west-2.amazonaws.com/s.cdpn.io/123548/p5.play.js)
And this is my test project (https://editor.p5js.org/MichelleCruz/sketches/bWsJIr_zQ), I do not know why it is having this behaviour, I hope I can have an answer soon

Thanks in advance

**Comment by molleindustria** [comment]
I think it's this the issue described here?
https://github.com/molleindustria/p5.play/issues/136

> SOLUTION :
> 
> In P5.PLAY.JS locate the line 3571
> where you have :
> pInst.image(this.spriteSheet.image, frame_info.x, frame_info.y, frame_info.width, frame_info.height, this.offX, this.offY, frame_info.width, frame_info.height);
> 
> change it to :
> 
> pInst.image(this.spriteSheet.image, this.offX, this.offY, frame_info.width, frame_info.height, frame_info.x, frame_info.y, frame_info.width, frame_info.height);

@islemaster is there a reason the parameters weren't swapped? I'm afraid of making changes

**Comment by GabriMagic** [comment]
Yeah!! This was the problem, now it works perfectly!!

I do not understand why if it code is wrong, the repository is not updated?

I purposed the change to the file, I hope to accept this change, and use the github file as cdn, how It should be.

Thanks for the gelp :)
