### ISSUE TITLE
overlapPixel example not working

### ISSUE THREAD

**Issue by mrjoshida** [molleindustria/p5.play#18]
In the [point and pixel overlap example](http://p5play.molleindustria.org/examples/index.html?fileName=collisions5.js#) it looks like overlapPixel is not working - the poor triangle falls straight through the platform.

**Comment by molleindustria** [comment]
Yeah I noticed that, I think something in p5's get() changed and broke it. I'll check it as soon as I can

**Comment by mrjoshida** [comment]
Looks like it's been fixed in p5.js https://github.com/processing/p5.js/issues/342 , pulling an updated version fixes the example

**Comment by toolness** [comment]
Thanks @mrjoshida! It looks like the p5.play website now uses `p5.js v0.4.21 January 04, 2016`, which should include that fix, as the triangle is no longer falling straight through the platform. I'm going to close this issue now, but feel free to re-open it if you disagree.
