### ISSUE TITLE
Error message running a p5.play sketch on OpenProcessing

### ISSUE THREAD

**Issue by ricardocanada** [molleindustria/p5.play#180]

**Comment by ricardocanada** [comment]
I get this message in the console each time I run the sketch.
"You just changed the value of "camera", which was a p5 function. This could cause problems later if you're not careful." It doesn't affect playback now, but note the warning.

**Comment by rafaelfajardo** [comment]
I get this error message on OpenProcessing, too. I see it also on a sketch I began on OpenProcessing and have set up to run locally on my laptop served via Node.js simple-server and local P5.js and local P5.play.js.

**Comment by aditirepo426** [comment]
> I get this message in the console each time I run a p5.play sketch.
> "You just changed the value of "camera", which was a p5 function. This could cause problems later if you're not careful." It doesn't affect playback now, but note the warning.

THIS DOESN'T AFFECT THE PROGRAM BUT

**Comment by quinton-ashley** [comment]
updates to this issue will be in #195

**Comment by rafaelfajardo** [comment]
Thank you Quinton and Paolo
Paz,
Rafael
