### ISSUE TITLE
How does rotateToDirection work in practice?

### ISSUE THREAD

**Issue by mihalski** [molleindustria/p5.play#181]
As an example of the difficulty I am having with is:

https://editor.p5js.org/michal.dobrzynski/sketches/4vbAkrVY4

Is there a way (other than rotating the original image by 90 degrees) to make the ship face the direction of movement (i.e. "North")?

I can find no explanation as to how to use this method and by default it does not do what is expected.

**Comment by SnipedCode** [comment]
Why don't you rotate your image source?
(playerShip1_red.png)

**Comment by molleindustria** [comment]
Assigning a the rightward direction to 0  degrees is a common although counterintuitive convention (because of radians etc)
The easiest way is to get rid of the rotateToDirection and add this to the update function:
playerSpr.rotation = playerSpr.getDirection()+90;

**Comment by mihalski** [comment]
@molleindustria Thanks for that suggestion. Clean and works great!
