### ISSUE TITLE
Tile System

### ISSUE THREAD

**Issue by Suxsem** [molleindustria/p5.play#186]
Hello, I don't know if I cannot find this function or if it's not present...

I want to repeat an image to fill the sprite.

For example, I want to create the ground for a platform game. I would just create an image with a small width and then repeat it for the whole width of the window.

I think it's a common use case, what do you think?

**Comment by molleindustria** [comment]
You may be thinking about a tile system or a tiled texture. The first isn't provided by p5.play (consider phaser.js for that and for platformers), the second would be efficient only in engines that are natively 3D like Unity, and draw 2D images as textures. You can make your own draw function that tiles images but I believe it wouldn't be much faster that drawing a lot of sprites.

**Comment by Suxsem** [comment]
I did it with multiple sprites grouped, thanks!

**Comment by quinton-ashley** [comment]
I will add a tile system to p5.play once I'm sure I've made a really good one, stay tuned!
