### ISSUE TITLE
Typescript type declaration file

### ISSUE THREAD

**Issue by l0g1c4p3** [molleindustria/p5.play#189]
Is anyone aware of a type declaration file for p5.play, or if there are any plans to create one?

I am trying to adopt the library for a research project, but I really want to use pure typescript and would much rather not mix it with untyped js.

Many thanks for any info you can provide

**Comment by molleindustria** [comment]
NEVER

**Comment by l0g1c4p3** [comment]
Fair enough, Paolo  :)
It would be good to include this strong policy statement at the top of the documentation as a courtesy, so that people can be aware of it.  Since p5.js does provide type declarations as standard, people would be excused to assume p5.play.js may do the same.

Unfortunately - as typescript is increasingly widely adopted and I need to future-proof my efforts - it's a deal breaker for me.

**Comment by molleindustria** [comment]
Well, I meant... I don't really maintain this repository. Perhaps somebody would want to add that, whatever it means.

**Comment by GoToLoop** [comment]
Alternatively we can make the "p5.play.js" comments conform to JSDoc, so it is understandable by TypeScript: :bulb:
https://www.TypeScriptLang.org/docs/handbook/type-checking-javascript-files.html#supported-jsdoc
