### ISSUE TITLE
Group displacement (currently only works for the first sprite)

### ISSUE THREAD

**Issue by theneuetimes** [molleindustria/p5.play#191]
I'm making a game where there are multiple sprites moving independently and I need them to be able to displace each other freely. The issue is that doing something as simple as `players.displace(players)` will only allow the first sprite from the group to displace others, while the last one is not allowed to move any others. I've made a simplified sketch to show the issue:

https://editor.p5js.org/cal1fxrniaaa/sketches/9oivOp7bc
(click mouse to move a different square)

As you can see, square 0 can move all the other ones, square 1 can only move square 2, and square 2 cannot move anything.

Edit: if the link is dead, here's the code:
```js
let curr = 0;
let players;

function setup() {
  createCanvas(400, 400);
  
  players = new Group();
  
  for(let i=0; i<3; i++) {
    console.log(i);
    players.add(new Sprite(random(width), random(height), 40, 40));
    
    players[i].draw = () => {
      fill(0);
      rect(0, 0, 40, 40);
      fill(255);
      text(i, 10, 10);
    }
  }
}

function draw() {
  background(220);
  
  text(curr, 10, 20);
  
  players.displace(players);
  
  drawSprites(players);
  
  players[curr].position.x = mouseX;
  players[curr].position.y = mouseY;
}

function mousePressed() {
  curr = curr >= players.length-1 ? 0 : curr+1; 
}

```

**Comment by molleindustria** [comment]
Yes, that is a known limitation :(

**Comment by quinton-ashley** [comment]
I got the example to work by making the cursor Sprite a separate sprite. Still a little wonky when pushing the boxes against each other, some cases it'll push both, other cases not.

```js
let curr = 0;
let players;
let cursor;

function setup() {
	createCanvas(400, 400);

	players = new Group();

	for (let i = 0; i < 3; i++) {
		console.log(i);
		players.add(new Sprite(random(width), random(height), 40, 40));

		players[i].draw = () => {
			fill(0);
			rect(0, 0, 40, 40);
			fill(255);
			text(i, 10, 10);
		};
	}
	cursor = players[0];
}

function draw() {
	background(220);

	text(curr, 10, 20);

	cursor.displace(players);
	players.displace(players);

	drawSprites(players);

	players[curr].position.x = mouseX;
	players[curr].position.y = mouseY;
}

function mousePressed() {
	curr = curr >= players.length - 1 ? 0 : curr + 1;
	cursor = players[curr];
}

```

**Comment by quinton-ashley** [comment]
This problem will be fixed in v3 of p5.play, see this example:
https://molleindustria.github.io/p5.play/examples/v3.html?fileName=displace.js

**Comment by theneuetimes** [comment]
That's great news! Any planned release date or a list of new features for v3?

**Comment by quinton-ashley** [comment]
I don't know when it will get released yet but I will make a features list!

**Comment by quinton-ashley** [comment]
Here is the list, I will add more later :)

https://github.com/molleindustria/p5.play/wiki/New-Features-in-p5.play-Version-3

**Comment by quinton-ashley** [comment]
@theneuetimes I'll be releasing p5.play v3 this month!

**Comment by theneuetimes** [comment]
❤️
