### ISSUE TITLE
sprite cull function

### ISSUE THREAD

**Issue by garyanikin** [molleindustria/p5.play#192]
Hi guys 👋 
How to clean up offscreen Sprites in proper way?

I added this code in my project to clean up sprites
```js
  function isSpriteOffscreen(sprite) {
    const { width, height } = p; // p5 variable
    const { originalHeight, originalWidth, position } = sprite;
    const { x, y } = position;

    return (
      x < 0 - originalWidth ||
      x > width + originalWidth ||
      y < 0 - originalHeight ||
      y > height + originalHeight
    );
  }

  function draw() {
    drawSprites();

    // clean up offscreen sprites
    const sprites = getSprites();
    sprites.forEach((sprite) => {
      if (isSpriteOffscreen(sprite)) {
        removeSprite(sprite);
      }
    });
  }
```

**Comment by quinton-ashley** [comment]
This could be a very useful method for many types of games. I will add a cleanup function to the Group class that could be run in the draw function.

**Comment by quinton-ashley** [comment]
Here is the documentation for the new cull method of the Group class!

http://127.0.0.1:5501/docs/classes/Group.html#method-cull

I also added an example:

https://molleindustria.github.io/p5.play/examples/index.html?fileName=culling.js
