### ISSUE TITLE
[enhancement] Draw Sprites automatically

### ISSUE THREAD

**Issue by dipamsen** [molleindustria/p5.play#194]
Instead of having to call `drawSprites()` at the end of the `draw` function, it can be handled automatically in the library by using 
```js
p5.prototype.registerMethod('post', p5.prototype.drawSprites)
```
([p5 registerMethod](https://github.com/processing/p5.js/blob/main/contributor_docs/creating_libraries.md#use-registermethod-to-register-functions-with-p5-that-should-be-called-at-various-times))

In this way, the drawSprites will be called after every frame.

We can also make `Sprite.prototype.show` property which states whether the sprite should be drawn automatically, (or can be drawn by manually calling `sprite.draw()`)

**Comment by molleindustria** [comment]
The idea is that you may want to decide when to draw the sprites or a group of sprites in the "draw" function so you can integrate them with the standard p5 stuff.
