### ISSUE TITLE
loadAnimation() fails parsing filenames with short non-numeric prefix

### ISSUE THREAD

**Issue by myselfhimself** [molleindustria/p5.play#197]
Hello,
for a call like:
`var cog1 = loadAnimation('sprites/food/level3/bricks/cog0001.png', 'sprites/food/level3/bricks/cog0002.png');`
an error will be raised by p5.js:
`Warning undefined frame 0`

Step by step debugging of p5.play.js shows:
```

               var digits1 = 0;
                var digits2 = 0;

                //skip extension work backwards to find the numbers
                for (i = from.length-5; i >= 0; i--) {
                    if(from.charAt(i) >= '0' && from.charAt(i) <= '9')
                        digits1++;
                }

                for (i = to.length-5; i >= 0; i--) {
                    if(to.charAt(i) >= '0' && to.charAt(i) <= '9')
                        digits2++;
                }

// DIGITS1 AND DIGITS2 VARIABLES EVALUATE TO 5

                var prefix1 = from.substring(0, from.length-(4+digits1));
                var prefix2 = to.substring(0, to.length-(4+digits2) );

PREFIX1 AND PREFIX2 BOTH EVALUATE TO  "sprites/food/level3/bricks/co"
```

I suspect that the issue is related to the filename prefix is too short (cog) vs. the `4+digits1` hardcoded substring value which should be computed dynamically instead.

:)

**Comment by molleindustria** [comment]
Sorry, I can't reproduce that. I encounter no issues when using assets named cog0001 etc

**Comment by myselfhimself** [comment]
Hello, the issue actually lies if there is one or more digits in the whole path before the file name itself.

See screenshot excerpt below:
![image](https://user-images.githubusercontent.com/1265346/119733444-d0e63480-be79-11eb-92bf-fec7ed678a55.png)

In such conditions, for my file names to be taken into account.. I have to rename them with an additional padding 0 and have my loadAnimation() calls use one 0 of padding fewer as reality...

In my above comment's code excerpt, variables digits1 and digits2 should be computed on `from.substr(from.lastIndexOf("/"))` and `to.substr(from.lastIndexOf("/"))`, that is to say on the filename without directory paths included.

**Comment by myselfhimself** [comment]
This does prevent me from telling you, thanks for p5.play!! It spares me a lot of work.. :)

**Comment by myselfhimself** [comment]
Related to https://github.com/myselfhimself/BerlinWallBreaker/issues/1

**Comment by myselfhimself** [comment]
This is fixed in this PR https://github.com/molleindustria/p5.play/pull/175

**Comment by myselfhimself** [comment]
I can try to make a new fresher PR or alter it

čt 27. 5. 2021 v 14:25 odesílatel Paolo Pedercini ***@***.***>
napsal:

**Comment by myselfhimself** [comment]
I created a simpler PR thanks to @keithohara 's former work on PR #175 , feel free to merge.
I tested the new PR manually it works well.

**Comment by molleindustria** [comment]
Thank you so much!

**Comment by myselfhimself** [comment]
Thank you too!
