### ISSUE TITLE
Is there a Typescript version of p5.play?

### ISSUE THREAD

**Issue by YamiAtem** [molleindustria/p5.play#198]
Is there a p5.d.ts file for p5.play.js as this very helpful for writing p5.play in typescript and also for teaching. So is there any p5.play.d.ts file or will there be any in the future?

And yes I have tried to compile them myself but it doesn't work it just says:
`export {};`
After being generated

**Comment by quinton-ashley** [comment]
Try again I just did a big update of p5.play to use ES6 classes! There are no plans currently to offer a Typescript version of p5.play though.
