### ISSUE TITLE
Why are Sprite images slightly fuzzy?

### ISSUE THREAD

**Issue by bendavis78** [molleindustria/p5.play#202]
When drawing an image-based sprite, the image becomes slightly fuzzy. The screenshot below shows 2 images, the one on top was drawn with `image()` and the bottom one was drawn with a sprite:

![image](https://user-images.githubusercontent.com/324392/117081047-b5698d00-ad04-11eb-9702-18d8adccce0e.png)

```javascript
let shipImage, ship;

function preload() {
    shipImage = loadImage('assets/playerShip1_blue.png');
}

function setup() {
    createCanvas(600, 800);

    // create the ship sprite
    ship = createSprite(300, 700, 99, 75);
    ship.addImage(shipImage);
}

function draw() {
    // set the background to black
    background(0);
    image(shipImage, 300-(99/2), 550);
    drawSprites();
}
```

**Comment by guschnwg** [comment]
On `setup()` call `noSmooth()` after create the canvas

**Comment by quinton-ashley** [comment]
Here's the noSmooth reference:
https://p5js.org/reference/#/p5/noSmooth
