### ISSUE TITLE
overlapPixel function does not work for scaled or rotated sprites

### ISSUE THREAD

**Issue by BhavyamGoyal** [molleindustria/p5.play#205]
overlapPixel function does not work for scaled or rotated sprites it only works for rotation == 0 and scale == 1

**Comment by quinton-ashley** [comment]
Yeah it'd be nice if this was fixed. Maybe in the far future I will look into it.

**Comment by quinton-ashley** [comment]
I don't think I will add this to p5.play v3 because it would be simpler if users just used sprites to check for all collisions.
