### ISSUE TITLE
Error: Cannot read property 'touches' of undefined

### ISSUE THREAD

**Issue by quinton-ashley** [molleindustria/p5.play#206]
p5.min.js:3 Uncaught TypeError: Cannot read property 'touches' of undefined
    at _.o.default._updateTouchCoords (p5.min.js:3)
    at _.p5._updateNextTouchCoords (p5.play.js:265)
    at _.p5._onmousedown (p5.play.js:302)

**Comment by scenaristeur** [comment]
just commenting the line 265 in your p5.play.js seems to fix that issue
```  //  this._updateTouchCoords();
```

**Comment by quinton-ashley** [comment]
oops, closing haha
