### ISSUE TITLE
Cannot read properties of undefined (reading '_report')     at undefined:2:287964

### ISSUE THREAD

**Issue by ggarvo** [molleindustria/p5.play#208]
Using p5.play and this appears in console:
TypeError: Cannot read properties of undefined (reading '_report')
    at undefined:2:287964

**Comment by ACIDULATED** [comment]
same error

**Comment by weeaudi** [comment]
Yep also the same trying to use jsmpeg-vnc-linux

**Comment by quinton-ashley** [comment]
Seems like it was probably an issue with a specific version of p5.js or something else. p5.play does not have a _report property.
