### ISSUE TITLE
Animations not showing.

### ISSUE THREAD

**Issue by ACIDULATED** [molleindustria/p5.play#209]
function setup() {
    createCanvas(800, 400);
    var Rick = createSprite(200, 200);
    Rick.addAnimation('rickroll', 'assets/rick.png', 'assets/rick.png');
}

function draw() {
    drawSprites();
}

This should add the rickroll image saved in my assets, but it doesn't. Instead, it's a white screen.

**Comment by molleindustria** [comment]
just add it once
Rick.addAnimation('rickroll', 'Rick.png');

**Comment by quinton-ashley** [comment]
Check the size of your image file, is it a large file with a lot of transparency around it? Also you could use the addImage function instead. Generally it's also better to load images in the preload p5.js function.

Provide a zip of your project if you need more help, closing this issue for now.
