### ISSUE TITLE
Sprites do not automatically update in an instance mode draw loop

### ISSUE THREAD

**Issue by lucwhite** [molleindustria/p5.play#210]
Had an issue with p5 play sprite animations not playing with p5 in instance mode.

It's a pretty specific bug but with p5 in instance mode, the `spriteName.update()` function is not automatically called at the start of the `draw` loop. It has to be called manually. 

Maybe this could be added as a side note in the docs.

**Comment by quinton-ashley** [comment]
I think this was fixed.
