### ISSUE TITLE
p5 had problems creating the global function "Animation"

### ISSUE THREAD

**Issue by TheGreenSheeep** [molleindustria/p5.play#211]
Whenever I try to run my program it comes up with the following errors:

p5.js says: p5 had problems creating the global function "Animation", possibly because your code is already using that name as a variable. You may want to rename your variable to something else. (http://p5js.org/reference/#/p5/Animation)

You just changed the value of "camera", which was a p5 function. This could cause problems later if you're not careful.

I understand that this is the same question as #195, but I am practically brand new to P5 and don't understand how to fix it. I haven't included any code snippets because I have no references to Animation and I haven't yet integrated any p5.play script into my program.

**Comment by TheGreenSheeep** [comment]
Managed to fix it. For some reason, by exchanging the p5.js file for the p5.min.js file fixed it but not sure why.

**Comment by quinton-ashley** [comment]
Animation has already been renamed to SpriteAnimation. Issue solved!
