### ISSUE TITLE
Sprite with loaded image not showing

### ISSUE THREAD

**Issue by XytheRoblox** [molleindustria/p5.play#213]
I have all the libraries included

I checked working examples and adjusted my code

My code: 
[gtproject.zip](https://github.com/molleindustria/p5.play/files/8459819/gtproject.zip)
)

**Comment by quinton-ashley** [comment]
I found the problem, your image has too much transparent space around it. Edit the image to remove the transparent space and you will see it. Also p5.play createSprite x and y coordinates are for the center of the image.
