### ISSUE TITLE
Usage as a module

### ISSUE THREAD

**Issue by obadakhalili** [molleindustria/p5.play#217]
Hey. I need to use this package with Vite, and Vite can't import it because it's not defined as a module but rather as a script. Is there a way to get around that?

**Comment by obadakhalili** [comment]
Here's what I've for now https://www.npmjs.com/package/@obadakhalili/p5.play.

**Comment by quinton-ashley** [comment]
I'll add this soon. I should have the p5.play package be require-able for node.js too.

**Comment by GoToLoop** [comment]
You should consider using ECMA module rather than Common JS so it's compatible to both browser & NodeJS.

**Comment by quinton-ashley** [comment]
@GoToLoop In the browser I don't want p5.play to be a module though, it needs to keep automatically attaching itself to a p5 instance.

Now that I'm thinking about it what would be the use case in NodeJS that someone would need to require p5.play hmm idk

**Comment by quinton-ashley** [comment]
@obadakhalili  Could you actually try having p5.play be a module export but still have it work in the browser automatically for people that just add it via script tag in html?

**Comment by quinton-ashley** [comment]
@obadakhalili Can you try the latest version, v2.2.9 ? I think I fixed this.
