### ISSUE TITLE
sprite.MirrorX not working?

### ISSUE THREAD

**Issue by abrahamavnisan** [molleindustria/p5.play#219]
Could it be that the code beneath the sprite.mirrorX and sprite.mirrorY functions is no longer working in the latest version of the p5.play library? 

Reading the code [in this example](http://molleindustria.github.io/p5.play/examples/index.html?fileName=sprites_with_sheet.js) on http://molleindustria.github.io, I believe the character should be changing the horizontal direction they are facing depending on the mouse position.

I'm having the same issue [in this example](https://editor.p5js.org/abrahamavnisan/sketches/d4eeKzhdD) that I created using the p5 web editor. (Use the letters 'a' and 'd' to move the character to the right and left - he should be flipping horizontally when moving to the left).

I recall this working in earlier versions of the p5 play library, which is partly why I think this may be a bug.

Thank you to all who have contributed to this terrific library! I love using it to teach creative coding :)

**Comment by quinton-ashley** [comment]
Sorry! That example was wrong but I just fixed it. In version 2 of p5.play mirrorX is a function.

```js
// mirrored
sprite.mirrorX(-1);

// not mirrored
sprite.mirrorX(1);
```

In version 3 of p5.play mirrorX will be a property that can be set to true or false because I think that makes more sense than using numbers for it.
