### ISSUE TITLE
createSprite() not defined

### ISSUE THREAD

**Issue by xDarkAngelXD** [molleindustria/p5.play#220]
I host a class and I was creating a template for the students when I came upon a error that states createSprites() is not declared in the current scope

How do I fix this error I compared the code with a working project and it is exactly the same

Any help will be appreciated 

This is the code in script.js

`var playerPaddle

playerPaddle = createSprite(50, 50, 50,50)
playerPaddle.shapeColor = "black"

function draw(){
	background("white")
	drawSprites();
}`

And the code in index.html

`<!DOCTYPE html>
<html>
<head>
	<meta charset='utf-8'>
	<meta http-equiv='X-UA-Compatible' content='IE=edge'>
	<title>Page Title</title>
	<meta name='viewport' content='width=device-width, initial-scale=1'>

</head>
<body>
	
	

	<script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.9.0/p5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.9.0/addons/p5.dom.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.9.0/addons/p5.sound.min.js"></script>
    <script src="p5.play.js"></script>
	<script src="script.js"></script>
	<script src="p5.js"></script>
	<script src="p5.min.js"></script>
	<script src="p5.sound.min.js"></script>
	<script src="p5.sound.js"></script>

	

	<script src="script.js"></script>

</body>
</html>`

**Comment by quinton-ashley** [comment]
Upgrade your p5.js file requests to get the latest version, v0.9.0 of p5js is too old! That should fix your issues, if you have any other problems let me know!

**Comment by quinton-ashley** [comment]
The latest version is 1.4.2

https://cdnjs.com/libraries/p5.js

**Comment by xDarkAngelXD** [comment]
I am still getting the error of createSprite() is not defined

**Comment by quinton-ashley** [comment]
Sorry I didn't notice this yesterday but the other problem is that you're importing p5.js multiple times. It can only be imported once so either have it load from the CDN or from the file folder, you can't do both. I made a template project for you so just copy this!

[](https://editor.p5js.org/quinton-ashley/sketches/R7mQTQzXO)

**Comment by xDarkAngelXD** [comment]
I used you template import lines but now the error is that draw sprites is not defined

**Comment by xDarkAngelXD** [comment]
The error is still there

**Comment by quinton-ashley** [comment]
Try copying the whole template file and just use that to get started.

**Comment by quinton-ashley** [comment]
You can't use `createSprite` before the p5.js setup function gets run.

**Comment by xDarkAngelXD** [comment]
Thanks for the help

Also, I was trying to make one of the sprites move based on the keyboard and I wrote the following code

`
function playerMovements(){
	if(keyDown("a")){
		playerPaddle.x = playerPaddle.x-10;
	}
}
`

But I come across an error stating that it cannot read properties of undefined (reading 'x')

I declared a global variable but it would still give an error

**Comment by quinton-ashley** [comment]
Version 2 (and previous versions) of p5.play require you to use sprite.position.x

In Version 3 I made it so sprite.x works. I'm going to release v3 by the middle of August!
https://editor.p5js.org/quinton-ashley/sketches/szN_XdV5O

Check out all the different examples for each version.
https://molleindustria.github.io/p5.play/

**Comment by xDarkAngelXD** [comment]
Thank you for you help I truly appreciate it 

If I have any more problems I will reach out to you!
