### ISSUE TITLE
Error in V3 example

### ISSUE THREAD

**Issue by dethe** [molleindustria/p5.play#221]
When I run the V3 example at https://editor.p5js.org/quinton-ashley/sketches/szN_XdV5O I get the following error: `Error: The old p5.js preload function can't be used with p5.play. Use an async setup function instead.`

Full stack trace: 

```
Error: The old p5.js preload function can't be used with p5.play. Use an async setup function instead.
    at p5PlayInit (https://molleindustria.github.io/p5.play/v3/p5.play.js:3944:9)

    at [264]</_/< (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.2/p5.min.js:3:431469)

    at _ (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.2/p5.min.js:3:431435)

    at [261]</< (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.4.2/p5.min.js:3:420505)
```

This is on Windows 10 running in Firefox 103.0.

**Comment by quinton-ashley** [comment]
Yes sorry I was doing a big update. You must've tried it at just the wrong time hehe. Try it out now!

**Comment by quinton-ashley** [comment]
Also check out some of the other v3 examples on the website. I figure that for a library like this using async/await for loading is going to be way better and it became part of JavaScript several years ago now so kids should learn how to use it. I'll post a full explanation later.

**Comment by dethe** [comment]
When I try that sketch now I don't get an error, but I don't see a sprite when I click either. I'm going to assume it is because things are still in flux. It's great to see this library back under active development, thanks for taking it on!

**Comment by quinton-ashley** [comment]
Yeah I did some more big changes. I realized doing an async setup function was a bad idea. Most of the examples should work now as well as the starter template.
