### ISSUE TITLE
Bugs in v3 examples (Pong and Breakout)

### ISSUE THREAD

**Issue by hakmad** [molleindustria/p5.play#222]
I'd just like to preface this by saying that I don't know anything about `p5` or JavaScript, so take anything I say with a grain of salt.

The `ball` object has a really weird behaviour - everytime it contacts another object (e.g. a `brick` in the Breakout example or the `paddleA`/`B` in the Pong example), the speed decreases significantly. I tried to log the speed with `console.log` to no avail, but I'm guessing the issue is caused by something wrong with either the `setSpeed` method of the ball or the `swing` variable/`bounce` method doing something...weird. 

Like I said, I don't know anything about JS/`p5`, I just think this project is pretty cool! This is on Firefox 103.0, Windows 10 by the way.

**Comment by quinton-ashley** [comment]
yeah my bad, I should have those games marked as [TODO]. I haven't convert them to v3 yet!

**Comment by hakmad** [comment]
A little more experimentation, and I think it's a problem with the `bounce` method. Removing the `swing` variable and forcing the ball to "reflect" off of the surface by doing:

```
if (ball.bounce(paddleA)) {
	ball.setSpeed(MAX_SPEED, ball.getDirection() + 180);
}

if (ball.bounce(paddleB)) {
	ball.setSpeed(MAX_SPEED, ball.getDirection() - 180);
}
```

Results in the same behaviour.

**Comment by quinton-ashley** [comment]
most of the examples are working again!
