### ISSUE TITLE
sprite.position.y undefined

### ISSUE THREAD

**Issue by xDarkAngelXD** [molleindustria/p5.play#223]
I am creating a game that is for my sister and when I was trying to make the sprite jump it would go blank and display an error that it cannot read sprite.position.y

`	if(keyCode === UP_ARROW && melon.position.y >=10){
		 melon =  melon.position.y-10;
	  }`

It would help out a ton if you help me in this issue

**Comment by quinton-ashley** [comment]
Use melon.y ! Also make sure you're creating the melon before that code
runs.

**Comment by quinton-ashley** [comment]
Could you share the rest of your code?

**Comment by quinton-ashley** [comment]
also what version of p5.play are you using?

**Comment by xDarkAngelXD** [comment]
I am using v3 of p5.play and I created the melon in function setup

Here is the rest of the code

`//Variables
let melon, melonIMG, melonRunner, melonCollided
let JJ, Bingo, YoYo, TomTom, Dad, Mom
let clouds, cloudIMG, ground, invGround, groundIMG

function preload(){

	//Runner
	melonIMG = loadImage(" melon.png");

	//Background
	groundIMG = loadImage(" ground.png");
	cloudIMG = loadImage(" cloud.png");

	//Obstacles
	JJ = loadImage(" jj.png");
	Bingo = loadImage(" bingo.png");
	YoYo = loadImage(" yoyo.png");
	TomTom = loadImage(" tomtom.png");
	Dad = loadImage(" dad.png");
	Mom = loadImage(" mom.png");

}

function setup(){
	createCanvas(400,600);

	melon = createSprite(50,160,20,50);
	melon.addImage(melonIMG);
	melon.scale = 0.2

	ground = createSprite(200,220,400,20);
	ground.addImage("ground",groundIMG);
	ground.x = ground.width /2;
	ground.velocityX = -4;
	ground.scale=0.4
  
	invGround = createSprite(200,220,400,10);
	invGround.visible = false
	melon.collide(invGround)

}

function draw(){
	background("skyblue");

	if(kb.pressed('up') && melon.position.y >=10){
		 melon =  melon.position.y-50;
	  }
	  
	  
	  
	  //+0.8 Gravity
	  if(melon.position.y <= 200){
	   melon.position.y =  melon.position.y+0.8
	  }
	
	  
	  if (ground.x < 0){
		ground.x = ground.width/2;
	  }

	melon.depth=ground.depth
	melon.depth+=1



	drawSprites();
}`

**Comment by xDarkAngelXD** [comment]
I tried you kb.pressed from the input methods you listed but it didn't work

**Comment by quinton-ashley** [comment]
whoops! The error was caused by a problem in my p5.play code for setting the scale of the sprite. Just fixed it so your code should work with p5.play v3.0.97

**Comment by quinton-ashley** [comment]
thank you for reporting this issue, if you have any other problems please let me know!

**Comment by xDarkAngelXD** [comment]
Thank you
