### ISSUE TITLE
keyboard input not working

### ISSUE THREAD

**Issue by xDarkAngelXD** [molleindustria/p5.play#224]
After the sprite.position.y was fixed the keyboard input methods (im using keyboard.pressed("up"))

Can someone pls help me in this issue

**Comment by quinton-ashley** [comment]
Do these examples work on the website? https://p5play.org/learn/input_devices.html

**Comment by quinton-ashley** [comment]
I can't repeat the problem and need more info on what OS and browser you are using.

**Comment by xDarkAngelXD** [comment]
Hi sorry I was away and I believe I was using an Hp windows 11 laptop

**Comment by quinton-ashley** [comment]
Is it still not working?
