### ISSUE TITLE
v2.0 documentation?

### ISSUE THREAD

**Issue by abrahamavnisan** [molleindustria/p5.play#229]
Hello,

I am an educator who has built some curriculum around the legacy 2.0 version of the p5 play library, and I'm wondering if the v2.0 documentation is still available somewhere? All I'm seeing on the website is the v3.0 documentation.

Thanks!

**Comment by quinton-ashley** [comment]
Access the old website here:

https://p5play.org/v2/index.html

and the v2 docs here:

https://p5play.org/v2/docs/index.html
