### ISSUE TITLE
Group has two clear methods in API, removeSprites not listed

### ISSUE THREAD

**Issue by creisman** [molleindustria/p5.play#23]
The API lists two clear methods. The code has @method clear on the removeSprites method. ![clear API](https://cloud.githubusercontent.com/assets/2438814/12709880/47b15308-c865-11e5-8180-fec5bff2e18f.png)
![clear documentation](https://cloud.githubusercontent.com/assets/2438814/12709881/47b1c702-c865-11e5-8e03-55d80c50670a.png)

**Comment by toolness** [comment]
Good catch, thanks for reporting this!

For reference, this discrepancy can be viewed live here:

http://p5play.molleindustria.org/docs/classes/Group.html#method-clear
