### ISSUE TITLE
Scale property with skin in Sprite

### ISSUE THREAD

**Issue by abusedmedia** [molleindustria/p5.play#232]
Hello there.

It looks like the `sprite.scale` property, when the Sprite has an image skin, doesn't work anymore.
Removing the skin it works as expected:

Example: https://editor.p5js.org/FabioFranchino/sketches/YXRBTf4Px

**Comment by quinton-ashley** [comment]
Yes I changed the way it works, now `sprite.scale` only changes the size of the sprite's collider. Check out this new example usage and explanation:

https://discord.com/channels/1003099076960723016/1009166111704633464/1052315887249657926

https://editor.p5js.org/quinton-ashley/sketches/rQZNY7-n6
