### ISSUE TITLE
Call removeSensors() when overlapped will crash

### ISSUE THREAD

**Issue by yoychen** [molleindustria/p5.play#233]
I want my player sprite can penetrate the static box during jumping up and detect ground during jumping down, so I use overlaps() to make my player can overlap static boxes and use removeSensors() to make my player can collide with static boxes. In some cases, like the sample below, when I click the up button, it will crash and can not do anything.

https://codesandbox.io/s/p5-play-removesensors-crash-ou759k

![CPT2212232152-687x531](https://user-images.githubusercontent.com/3905275/209347068-e73b9b0f-cb28-46cc-9f98-611464744f61.gif)

![image](https://user-images.githubusercontent.com/3905275/209346759-ad9846bf-1325-4664-8075-cd8d8a147792.png)

**Comment by quinton-ashley** [comment]
Oh yeah you can't remove the sensor mid-overlap, though perhaps it could be done afterwards if you use `sprite.overlapped`. I'll test that.

**Comment by quinton-ashley** [comment]
This works! This way is useful for if the player should be able to go through platforms from the bottom but enemies can't.
```js
player.overlapped(platform, () => {
	platform.removeSensors();
});
```

**Comment by quinton-ashley** [comment]
This function couldn't be placed in the draw loop because anytime overlapped is called it would make sensors on the platform.

**Comment by yoychen** [comment]
> For it to work, the overlapped function couldn't be placed in the draw loop because anytime overlapped is called it would make sensors on the platform.

Really? I see the example in the tutorial, It calls the overlaps() in draw loop.

https://p5play.org/learn/sprite.html?page=6

![image](https://user-images.githubusercontent.com/3905275/209444991-c8cf410f-852d-400e-852c-b6acf3733e9e.png)

**Comment by quinton-ashley** [comment]
The function itself would work in the draw loop as shown in the examples. Programmatically there's nothing wrong with doing that it wouldn't throw an error.

But... to achieve what you want to achieve it wouldn't work because if overlapped is called in draw it would create new sensors to detect an overlap if the sensors don't exist or were removed.

**Comment by yoychen** [comment]
I see. Really thanks for your help. 👍

**Comment by quinton-ashley** [comment]
You're welcome! Thanks for reporting the issue
