### ISSUE TITLE
Can not set the collider to 'static' when it was 'none'

### ISSUE THREAD

**Issue by yoychen** [molleindustria/p5.play#234]
I want my player sprite can penetrate the static box during jumping up and detect ground during jumping down, so I set the collider of all static boxes to 'none' to make my player can overlap static boxes and set the collider back to 'static' to make my player can collide with static boxes.
It can not be set back to 'static' when it was 'none', like the sample below.

https://codesandbox.io/s/p5-play-change-collider-crash-1l576w?file=/src/index.js:1189-1195

![image](https://user-images.githubusercontent.com/3905275/209348468-2e880fde-9d24-4f1d-9304-d626ff8c0222.png)

**Comment by quinton-ashley** [comment]
fixed in update v3.4.7!

**Comment by yoychen** [comment]
Thanks to fix that. look forward to the update. ❤️

**Comment by quinton-ashley** [comment]
If the platform had no collider, you could put this in the draw loop and it would change to static when the player is above the platform!
```js
if (player.y < platform.y) {
	platform.collider = 'static';
}
```
