### ISSUE TITLE
Weird collision with gravity and x/y lock

### ISSUE THREAD

**Issue by abusedmedia** [molleindustria/p5.play#235]
Hello there,

I'm facing an issue related to the physic engine solver in the following condition:
- There's a Sprite
- There's another Sprite with xLock and/or yLock true
- Gravity is not zero

The collision and bbox detection is wrong, here the sketch to show the issue:
https://editor.p5js.org/FabioFranchino/sketches/wjNPkXHpN

Keep this wonderful lib up!

**Comment by quinton-ashley** [comment]
Yeah I haven't documented those properties, `xLock` and `yLock`, for a reason haha. I tried implementing them a while ago but it didn't work properly, as your example shows. Now that I've learned more about planck I've realized that it's not possible to lock a dynamic sprite's x or y position in the same way as a rotation lock. I'm going to remove the `xLock` and  `yLock` properties from p5.play.

You can achieve positional locks by making a sprite's collider 'kinematic' or 'static' instead.
