### ISSUE TITLE
Sprite bounds and physics broken on concave polygons

### ISSUE THREAD

**Issue by kent12t** [molleindustria/p5.play#236]
I've been playing around with creating sprites using vertices just like the usual `beginShape()` `endShape()` methods but I have been stumped for a while until I figured out that some physics breaking and mouse detection not working at all on concave polygons.

[<img src="https://user-images.githubusercontent.com/34294530/215436415-30357ae9-d887-46b9-aa51-671dfc7a2ec9.png" height="200"/>](https://user-images.githubusercontent.com/34294530/215436415-30357ae9-d887-46b9-aa51-671dfc7a2ec9.png)
Upon drawing a concave sprite, the sprite fill does not work at all. While the item still falls down due to gravity, it acts as if it is a square sprite (lowest vertex as the base). *On a side note, if the same shape is drawn using a custom draw function, i.e. `thisBox.draw = () => { // insert vertices }}`, the base becomes the center of the vertices instead (mouse methods still broken regardless).*

[<img src="https://user-images.githubusercontent.com/34294530/215437564-c878bdc7-c5aa-4159-9e4a-add97bbac3b8.png" height="200"/>](https://user-images.githubusercontent.com/34294530/215437564-c878bdc7-c5aa-4159-9e4a-add97bbac3b8.png)
[<img src="https://user-images.githubusercontent.com/34294530/215437029-8211c606-25be-4797-a971-5cb8670615b9.png" height="200"/>](https://user-images.githubusercontent.com/34294530/215437029-8211c606-25be-4797-a971-5cb8670615b9.png) 
In comparison, when the shape is convex, the fill works just fine and it will fall to its side (counterclockwise).

Moreover, using any kind of `Sprite.mouse` functions such as `thisBox.mouse.hovering()` or `thisBox.mouse.pressing()` for the example above **does not work on the concave shape**, while fully working on convex shapes.

[Link to the p5.js sketch](https://editor.p5js.org/coffeeaddict/sketches/BSLsAmKei). Change the [20,20] vertex to [-20,20] or whatever else to see it working on convex shapes.

**Comment by quinton-ashley** [comment]
The concept that non-convex shapes like the stars will have chain colliders is described in the documentation.

https://p5play.org/learn/sprite.html?page=11

But it seems that I didn't really explain the difference between polygons and chains. Chains are made out of lines, the inside of a chain is empty. Planck doesn't allow concave shapes to have polygon colliders.

**Comment by quinton-ashley** [comment]
It could be possible to divide a concave shape into multiple convex shapes and sticking them together as one physics body. In the future that might be something I'd be interested in adding to p5.play.

**Comment by quinton-ashley** [comment]
I did notice an error creating a sprite with vertex mode that I'll fix in the next version!

**Comment by kent12t** [comment]
> It could be possible to divide a concave shape into multiple convex shapes and stick them together as one physics body. In the future that might be something I'd be interested in adding to p5.play.

Is there currently a janky way to do it in p5.play / p5? I started chopping up the parts but then sticking them back together as 1 physics body is wrecking my brain :(

**Comment by quinton-ashley** [comment]
The 'sprite.addCollider' function will be the way to make a sprite with multiple colliders manually. I haven't tested it at all yet though. I'll try finalizing it tomorrow.

Do you really need a concave collider for a game you're making?

**Comment by kent12t** [comment]
I will try that instead! Currently attempting some vector ray casting solutions to solve my problems. To be honest, the only thing i need is the `Sprite.mouse.pressing()` methods (and other sprite mouse methods) since it allows for a variable bounding box to detect mouse click/drag. I don't specifically need it as a physics solver atm!

**Comment by quinton-ashley** [comment]
Well don't try it yet, it wouldn't work. I'll let you know when I get it working!

**Comment by quinton-ashley** [comment]
I've made good progress on the `addCollider` function, it'll be ready soon.

**Comment by quinton-ashley** [comment]
I forgot to tell you that you can try using `addCollider` now! Only thing is sprites with multiple colliders can't have their collider type changed yet. I'll make that possible in a future version.
