### ISSUE TITLE
Group#removeSprites doesn't call remove on all sprites

### ISSUE THREAD

**Issue by creisman** [molleindustria/p5.play#24]
I noticed that calling Group#removeSprites wasn't actually calling Sprite#remove for all sprites. I think this is because of your implementation of remove.

array.removeSprites = function() {
  for(var i = 0; i<array.length; i++)
     array[i].remove();

  array.length = 0;
}

This loops over the length of the array and calls remove on sprites. However, because Sprite#remove also removes the sprite from all groups, when the next iteration of the loop happens, the group is now one shorter.

e.g. The group has two items in it, Sprite1 and Sprite2. Group#removeSprites is called. The loop has i=0, grabs the first element, and calls Sprite1.remove(). Sprite#remove removes the sprite from the group. The group now has one item in it. The loop completes and increments, so i=1, and group.length=1, so the loop terminates, even though it has one item in it.

While the last line, array.length=0 does make the group empty, it means that not all of the sprites are removed from other groups (particularly allSprites). Over a long period of time this begins to add up and results in the game slowing down.

Alternatives would be using a while loop to remove them or iterating from the back to the front.

**Comment by toolness** [comment]
Oh! This has actually been fixed by #13, but somehow the version of p5.play you're using doesn't include the fix... Where did you get your version of p5.js?  We'll need to have some kind of release process  to make sure that these fixes actually make it out the door, so I just filed #25 to address that.

Sorry for the inconvenience :disappointed:

**Comment by creisman** [comment]
Ah, good call. I didn't even think to check about an updated version. I was helping a friend debug her project and I think she pulled the live version as of ~October, which was before #13.
