### ISSUE TITLE
Sprites can be added to groups multiple times

### ISSUE THREAD

**Issue by toolness** [molleindustria/p5.play#37]
Not sure if this is a big deal, but I noticed it when I accidentally wrote the following code in a test:

```js
var mySprite = createSprite(1, 1);
allSprites.add(mySprite);

console.log(allSprites.length);
```

The number `2` will be logged to the console.

This is because `createSprite()` actually adds `mySprite` to `allSprites` on its own, so the call to `allSprites.add()` actually adds it *again*.

This could lead to weird behavior. For instance, since our current implementation of `Group#remove()` only removes the *first* reference to a sprite, this could result in unexpected behavior if someone's code calls it but it doesn't seem to "work" because another reference to the sprite still exists in the Group.

Not sure what we should do about this. Two options I can think of:

* Use the ES6 [`Set`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) class instead of `Array` for Groups, and use a [`Set` polyfill](https://github.com/WebReflection/es6-collections) when it's unavailable.

* Alternatively, if we want to keep as much backwards compatibility as possible, we could just add a check to `Group#add()` that first checks to see if the given sprite already exists in the group... The user could still shoot themselves in the foot in a number of ways since `Group` is also an `Array`, but at least we'd prevent the most common ways of doing so.

**Comment by islemaster** [comment]
Opened a PR with your second proposed solution.  I think `Set` is a good idea but it's also a major breaking change, and less of a 'beginner' concept - I think we keep it as an array for now.
