### ISSUE TITLE
Support for sprite sheets

### ISSUE THREAD

**Issue by karneaud** [molleindustria/p5.play#4]
Does your framework support spritesheets? which is more or less a common occurrence e.g. http://getsetgames.com/wp-content/uploads/2010/04/grossini_dance_atlas.png

**Comment by Jared-Sprague** [comment]
@karneaud I'm working on implementing this now! It depends on a yet un-released master branch of p5.js, so I'm just implementing it in a branch (goo.gl/v4WSZb) for now, but it should be ready soon! goo.gl/hcYbqW

**Comment by TheThirdOne** [comment]
+1 This is an important feature.

**Comment by paked** [comment]
:+1:

**Comment by Jared-Sprague** [comment]
Pull request: https://github.com/molleindustria/p5.play/pull/11

**Comment by paked** [comment]
:+1:
