### ISSUE TITLE
mouseUp, mouseDown, keyDown are inaccurate for 1 frame

### ISSUE THREAD

**Issue by toolness** [molleindustria/p5.play#43]
The folowing was originally noted in #42.

The documentation for `keyDown` states:

```
Like p5 keyIsDown but accepts strings and codes
```

However, the implementation is checking to see if the internal key state is specifically equal to `KEY_IS_DOWN`. The problem is that the internal keystate might actually be `KEY_WENT_DOWN`, in which case the method will retrun `false` but `keyIsDown()` will be `true`!

It's understandable that no one has noticed this, because it just means that the result of `keyDown` will be inconsistent with `keyIsDown` for only the frame in which the key went from up to down.

A parallel problem exists with `mouseDown`/`mouseIsDown`, as well as `mouseUp`.

@islemaster has some [thoughts](https://github.com/molleindustria/p5.play/pull/42#issuecomment-189685433) on it:

> I knew about this. I definitely want to fix it so keyDown and keyWentDown
> are not mutually exclusive states. I figured it wouldn't happen soon
> though, since it's technically a breaking change. I also want to check
> whether @molleindustria did this on purpose, to circumvent a certain set of
> beginner mistakes.
> 
> If we had a release process and semver I would bundle this with other
> breaking changes in a major version. Since things are still pretty fast and
> loose (and I don't think anyone auto-updates this library?) maybe we can
> just fix it.

**Comment by quinton-ashley** [comment]
@toolness @islemaster Is this still a problem?

**Comment by islemaster** [comment]
Hi @quinton-ashley! Thanks for maintaining here.  Yes, this was never addressed - the `keyDown` method still only checks for the `KEY_IS_DOWN` state, and its documentation hasn't changed.

https://github.com/molleindustria/p5.play/blob/b6ffefd86a9920e13f5248bb05da22df27332a5b/lib/p5.play.js#L3759-L3769

That said, I'm not sure it's a priority. 🤷 If we have no user complaints about this behavior it might be better to leave it.

**Comment by quinton-ashley** [comment]
Thanks! I will change this in v3. I made a wrapper for the p5.js keyIsDown function that converts key names to key codes, instead of reimplementing it.

**Comment by quinton-ashley** [comment]
wontfix for v2, closing this issue
