### ISSUE TITLE
Sprite and collider box are drawn off center

### ISSUE THREAD

**Issue by gtoast** [molleindustria/p5.play#48]
Issue: In latest release of p5.play sprite and collider box are drawn off center.

Here's an image of a sprite with debug turned on. The center is drawn correctly but the sprite itself is drawn as if rectMode is set to "CORNER" rather than "CENTER":
![collidertest_latest_release](https://cloud.githubusercontent.com/assets/280999/13886436/11e69ebe-ecf4-11e5-8ab4-2687404f4b23.jpg)

Here's the same sketch using the same version of p5.play that's used in the examples on the your website:
![collidertest_using_web_examples_release](https://cloud.githubusercontent.com/assets/280999/13886430/07ba5f70-ecf4-11e5-8d9b-a90a5ceb607e.jpg)

You can download the sketch used to create these images here:
[colliderTest.zip](https://github.com/molleindustria/p5.play/files/180124/colliderTest.zip)

You can recreate for yourself by downloading the latest p5.play release from the website.

**Comment by islemaster** [comment]
Thanks for bringing this to our attention!  This looks like a recent regression.  I'll take a look today.

**Comment by cpirich** [comment]
These constants are captured as globals too early. p5.js doesn't add those to the prototype until init time. We'll put together a PR to fix this:

```
  // These are p5 constants that we'd like easy access to.
  var RGB = p5.prototype.RGB;
  var CENTER = p5.prototype.CENTER;
  var LEFT = p5.prototype.LEFT;
  var BOTTOM = p5.prototype.BOTTOM;
  var PI = p5.prototype.PI;
```

**Comment by toolness** [comment]
Ahh yes! This is actually a [bug on P5's end](https://github.com/processing/p5.js/pull/1256#discussion_r52829838), but it'd be useful to fix in p5.play regardless since we want to support older versions of p5 if possible.

**Comment by gtoast** [comment]
Thank you guys! Much appreciated!
