### ISSUE TITLE
sprite moveTo function

### ISSUE THREAD

**Issue by karneaud** [molleindustria/p5.play#56]
Would be nice to have a moveTo method built in for easy basic directional movements 

e.g. 

```
setSpeed(1); // set the speed of movement
changeAnimation('run'); // set the animation 
moveTo(x,y[, rotation]); // moves the sprite to x,y values, rotation optional
```

**Comment by molleindustria** [comment]
A tweenning (in-betweening) type of movement would be cool but it sorts of conflicts with other kinds of movement and it would have to override them.

The example above can be resolved with very few lines of code but a moveTo function that specifies the duration of the interval and the type of progression (linear, ease in, ease out...) could be useful.

**Comment by quinton-ashley** [comment]
I've made a moveTo function as well as a moveTowards function for the upcoming p5.play v3:
https://molleindustria.github.io/p5.play/examples/index.html?fileName=displace.js
