### ISSUE TITLE
Remove built docs from repository

### ISSUE THREAD

**Issue by toolness** [molleindustria/p5.play#57]
It would be really nice if we could remove the built docs from the repository, so that we don't need to spam the commit history with rebuilds of the documentation whenever we change it. 

(This issue was split off from #41.)

**Comment by islemaster** [comment]
It'd be nice if this change was combined with/follows an improvement to our hosted docs situation.

**Comment by molleindustria** [comment]
I built the docs with yuidocs locally and then manually uploaded it. What do you people think is the best practice in terms of building / hosting it?

**Comment by islemaster** [comment]
I've been investigating that for some of my other projects.  There are a few approaches, but I haven't found one I love yet.

* We could always put together a process that commits the documentation automatically - [like the one described here](http://blog.brentjanderson.com/post/54687385443/grunt-yuidoc-and-continuous-documentation).  That requires we give a build system privileged commit access, and would run counter to the suggestion in this issue that we want to stop spamming the commit history with rebuilds.
* It would be cool if whatever machine is hosting the docs had a job that checked for changes and rebuilt them right there, but that assumes a lot about that machine and access to it, and would require occasional maintenance.
* I've been wanting to try a free service like [readthedocs.org](https://readthedocs.org/) but I don't think they support yuidoc and I can't find one that does.

All that to say, still brainstorming.

**Comment by toolness** [comment]
Another option is to use github pages to host the p5.play site and docs. This basically consists of:

* putting the website's static files in a `gh-pages` branch of this repository.
* Adding a `CNAME` file in the root of the `gh-pages` branch containing the text "p5play.molleindustria.org".
* @molleindustria would have to set up a CNAME DNS record for p5play.molleindustria.org that points to `molleindustria.github.io`.

The tricky part is basically getting the generated documentation into the `gh-pages` branch. Some projects I work on use `git subtree push` to push a subdirectory of the `master` branch as the root of the `gh-pages` branch, but I'm not a particularly big fan of this approach because it still requires the built site/docs to exist in the `master` branch in the first place (albeit a subdirectory of it).

It should be possible to write a script that generates the documentation, switches to the `gh-pages` branch and commits the documentation there, it's just tricky I guess. I've never written such a script myself but I know they exist.

**Comment by islemaster** [comment]
If we want to take a github pages approach, we might benefit from switching from YUIDoc to [JSDoc 3](http://usejsdoc.org).  The syntax is _really_ similar, a little less verbose, and the tooling options around it seem to be more robust.  Take a look at [jsdox](http://jsdox.org/) which generates markdown (appropriate for use on github pages) from JSDoc 3.

One major downside: The look/feel of the docs would change dramatically, and no longer match the p5.js docs.

**Comment by toolness** [comment]
> Take a look at [jsdox](http://jsdox.org/) which generates markdown (appropriate for use on github pages) from JSDoc 3.

Hmm, I'm confused about what you mean by "appropriate for use on github pages".  As far as I know, aside from [built-in support for Jekyll](https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/), GitHub Pages is largely just a way of serving static content, similar to e.g. Amazon S3. When I suggested using GitHub Pages, I didn't mean that we should also use Jekyll, although I suppose that is actually a possibility.

Do you mind if I take a stab at the GitHub Pages approach? This shouldn't be a very heavy lift, and it has the bonus of at least making a recent build of the documentation visible at http://molleindustria.github.io/p5.play/ (which is a 404 right now because we don't have a `gh-pages` branch).

**Comment by islemaster** [comment]
Oh, good point, my bad.  I was mixing up github pages with github wiki (re: markdown).

Go for it with the pages approach!
