### ISSUE TITLE
Bower support is broken

### ISSUE THREAD

**Issue by islemaster** [molleindustria/p5.play#61]
@karneaud just [reported on PR #8](https://github.com/molleindustria/p5.play/pull/8#issuecomment-202480197) that they:

"Tried to `install bower p5.play --save` and got

> ENOTFOUND Package p5.play not found

**Comment by karneaud** [comment]
`bower install --save https://github.com/molleindustria/p5.play.git` works if you are getting that bower 

> ECMDERR       Failed to execute "git ls-remote --tags --heads .....

error

**Comment by quinton-ashley** [comment]
use npm
