### ISSUE TITLE
Mark Sprite constructor as @private in docs?

### ISSUE THREAD

**Issue by toolness** [molleindustria/p5.play#63]
I was just reading through the docs and noticed that our `Sprite` constructor is documented as a public function.

However, another method we have to create sprites is the `createSprite` function, which actually seems preferable, because it adds the newly-created spite to `allSprites`. Should we actually deprecate using the `Sprite` constructor directly, or mention in its documentation that the reader will probably want to use `createSprite` instead?

**Comment by islemaster** [comment]
Yes, I suspect we should at least document it as such.  I'm not sure it's worth making it entirely inaccessible though.
