### ISSUE TITLE
Don't publish docs for private methods/properties

### ISSUE THREAD

**Issue by toolness** [molleindustria/p5.play#69]
Currently it seems our private methods and properties are documented by our YUIDocs. As far as I can tell, it seems this is because YUIDocs templates only remove entire classes and modules marked `@private` from their documentation output--not individual methods and properties. This is a bit of a bummer.

Some ways to get around this:
- Hack our copy of the theme. (Not a huge fan of this.)
- Somehow make it possible for the theme to not publish the private methods/properties, and push this functionality upstream. (This could take a while.)
- Make a yuidoc filter that removes the private methods and properties from the output `data.json` file. This is pretty straightforward and I've done something similar in https://github.com/processing/p5.js/pull/1295; it basically just consists of writing a node module that exports a function that takes the `data.json` blob and modifies it in whatever way it wants, after which YUIDoc will write it to disk.

**Comment by islemaster** [comment]
Alternative 4: Stop using YUIDoc :trollface:

**Comment by islemaster** [comment]
Solved by #150: Private methods are now hidden by default, and can be optionally displayed.
