### ISSUE TITLE
Document how to extend/subclass Sprite class

### ISSUE THREAD

**Issue by toolness** [molleindustria/p5.play#71]
Extending the Sprite class seems like something users of p5.play are very likely to want to do, especially since certain methods, like `draw()`, are documented as being override-able. So it seems like it might be useful to document a recommended way of doing this.

However, there doesn't actually seem to be a particularly easy way to make a proper subclass, as the only documented way to create a sprite is via the [`createSprite()`](http://p5play.molleindustria.org/docs/classes/p5.play.html#method-createSprite) function.

On top of that, while the Sprite class is accessible from code, due to the weird hacks I put in place to support instance mode in #22, accessing it actually always returns a constructor that is bound either to a specific p5 instance or `window`, which complicates subclassing even more. :sweat:

That said, some alternatives:
- Advise users to just make a factory function, e.g.:
  
  ``` js
  function createFunkyEnemy(x, y, pInst) {
    pInst = pInst || window;
    var sprite = pInst.createSprite(x, y, 50, 50);
    sprite.draw = function() { /* do stuff here */ };
    return sprite;
  }
  ```
- For more complex use cases, advise users to prefer [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance), e.g.:
  
  ``` js
  function FunkyEnemy(x, y, pInst) {
    pInst = pInst || window;
    this.pInst = pInst;
    this.sprite = pInst.createSprite(x, y, 50, 50);
    this.sprite.draw = this.draw.bind(this);
  }
  
  FunkyEnemy.prototype = {
    draw: function() {
      /* do stuff here */
    }
  };
  ```

Any other ideas?

**Comment by molleindustria** [comment]
I always use the first option (I didn't know they were called factory functions). I'm not sure that's really library-specific but in general a couple of general tutorials would be useful. 
The full game examples employ that type of extension: 
http://p5play.molleindustria.org/examples/index.html?fileName=asteroids.js

**Comment by swirly** [comment]
I understand the way of creating sprites via createSprite but why couldn't we just do the usual javascript way :
```
var mySprite = new Sprite(x,y,w,h); 
```
the additionnal part in createSprite function should be added directly in Sprite constructor. This way, we could create a type of particular sprites (asteroids, laser beams, and so on) by extending the sprite prototype. Or is my point of vue stupid ?

**Comment by quinton-ashley** [comment]
Extending Sprite was not possible until now. Users can easily subclass Sprite using ES6 extends or adding functionality to the prototype. Fixed in v2.0.1

**Comment by tuppercode** [comment]
Hi. Can someone post an example? I'm trying to extend the Sprite class and get the following:
[Player, line 1:](https://openprocessing.org/sketch/1771197#)Uncaught ReferenceError: Sprite is not defined

**Comment by quinton-ashley** [comment]
In p5.play v3 it's best to create a Group instead of extending the Sprite class. Here are some examples:

https://p5play.org/learn/Group.html

**Comment by davepinto** [comment]
I unfortunately have to use p5.play v2 in my university course this semester, and ran into the same issue as @tuppercode. Is there any way I could get class extension back on p5play v2? thank you

**Comment by davepinto** [comment]
I have to use p5.play v2 as part of my assessment requirements, but I was able to work around this in instanced mode:
```javascript
const sketch = function(p) {
    class Player extends p.Sprite {
        constructor(x, y, width, height = undefined) {
            super(x, y, width, height);
            this.customProp1 = "foo";
            this.customProp1 = "bar";
        }
    }
}
new p5(sketch, "p5canvas");
```

Hope this helps.

**Comment by quinton-ashley** [comment]
You could do the same in version 3
