### ISSUE TITLE
Allow a Sprite to be passed as the second argument to Sprite.setSpeed()

### ISSUE THREAD

**Issue by toolness** [molleindustria/p5.play#84]
I thought it might be neat to either add a new method or overload [`Sprite.setSpeed()`](http://molleindustria.github.io/p5.play/docs/classes/Sprite.html#method-setSpeed) like so:

``` js
setSpeed(speed, targetSprite)
```

This would just make the sprite move towards the `targetSprite` at the given `angle`.

This is just an idea, not sure how useful it'd be to our users.

**Comment by quinton-ashley** [comment]
Use the sprite.attractionPoint function, which can be given coordinates to another sprite.
