### ISSUE TITLE
Full support for angleMode(RADIANS)

### ISSUE THREAD

**Issue by islemaster** [molleindustria/p5.play#94]
In #91 @cpirich made p5.play check the p5 angleMode before doing conversions, so that internally we call p5 methods with the correct angle measurements.  However, p5.play methods still expect angles in degrees, regardless of what the p5 angleMode is.  It would be nice for p5.play's API to fully respect the angleMode, so that p5.play's methods take radians if angleMode(RADIANS), and degrees if angleMode(DEGREES).

This will be a breaking change, since p5's default angleMode is RADIANS but p5.play's API currently expects degrees.

I believe the complete set of public p5.play methods and properties that would require an API change are:
- `Sprite.rotation`
- `Sprite.rotationSpeed`
- `Sprite.setSpeed(speed, angle)`
- `Sprite.addSpeed(speed, angle)`
- `Sprite.getDirection()`
- `AABB.rotate(r)`
- `Animation.draw(x, y, r)`

**Comment by quinton-ashley** [comment]
Will fix in v3 by changing the default angle mode to DEGREES and respecting user changes to RADIANS
